[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=1000
OnRefreshAction=!Execute [!EnableMeasureGroup Timers][!UpdateMeasureGroup Timers]

[Variables]
@include=UserVariables.inc
@include2=TimeSettings.inc
ActionToTake=[Play #Sound_File#]["#Additional_Action#"][!ActivateConfig "#CURRENTCONFIG#"]
ActionToTakeSound=[Play #Sound_File#]
Launch=0

[MeasureNow]
Measure=Time
Group=Timers
UpdateDivider=-1
Disabled=1

[MeasureTotalSeconds]
Measure=Calc
Group=Timers
Formula=(#TimerHours# * 3600) + (#TimerMinutes# * 60) + #TimerSeconds#
UpdateDivider=-1
Disabled=1

[MeasureTarget]
Measure=Time
Group=Timers
Format=%#m/%#d/%Y %#H:%M:%S
TimeStamp=([MeasureNow:TimeStamp] + [MeasureTotalSeconds])
UpdateDivider=1
Disabled=1
DynamicVariables=1
OnUpdateAction=[Play#Ticking_Sounds# "tick.wav"][!SetVariable Target "[MeasureTarget]"][!UpdateMeasure MeasureLua]


[MeasureLua]
Measure=Script
Group=Timers
ScriptFile=#CURRENTPATH#Timer.lua
IfCondition=MeasureLua <= 0
IfTrueAction=#ActionToTake#
Disabled=1



[MeasureHours]
Measure=Calc
Formula=#TimerHours#


[MeasureMinutes]
Measure=Calc
Formula=#TimerMinutes#
RegExpSubstitute=1
Substitute="^(.)$":"0\1","^(.+)$":"\1"


[MeasureSeconds]
Measure=Calc
Formula=#TimerSeconds#
RegExpSubstitute=1
Substitute="^(.)$":"0\1","^(.+)$":"\1"




[img]
Meter=IMAGE
ImageName=Item.png
ToolTipText=Stop
LeftMouseUpAction=!ActivateConfig "#CurrentConfig#"
MouseActionCursor=1

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=107
h=140
MouseOverAction=!execute [!ShowMeter Plus][!ShowMeter Minus][!ShowMeter Menu][!ShowMeter Set][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Plus][!HideMeter Minus][!HideMeter Menu][!HideMeter Set][!HideMeter Close][!Redraw]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=80
Y=0
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=80
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"][!WriteKeyValue Variables Launch 0]
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=80
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[MeterTime]
Meter=STRING
X=44
Y=55
FontFace=Arial Black
FontColor=51,50,49
FontSize=17
StringAlign=CENTERCenter
StringStyle=BOLD
Antialias=1
Text="%1:%2"
MeasureName=MeasureMinutes
MeasureName2=MeasureSeconds
Group=TickTock
DynamicVariables=1

