[Metadata]
Name=RSS Gadget #1 | Feeds | Style 1
Config=Vista Rainbar | Feeds | RSS | Feeds | 1
Description=Displays the latest items from any RSS or Atom feed.
Instructions=Use the configuration tool to change your feed URL.
Version=5.0
Tags=Gadget | Feeds | Vista Rainbar | Feeds | RSS | Feeds | Feed
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
Author=legace@inbox.com

Update=60000


[img]
Meter=IMAGE
w=130
h=173
ImageName=..\img\Bkg.png
MouseActionCursor=0

[Solid]
Meter=STRING
solidcolor=0,255,0,1
w=140
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Close][!ShowMeter Set][!ShowMeter Plus][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Close][!HideMeter Set][!HideMeter Plus][!Redraw]

[Variables]

Substitute="":"","^\s+":"","<!\[CDATA\[":"","\]\]>":"","!\[CDATA\[":"","\]\]":""
get=<item>.*<title>(.*)</title>.*<link>(.*)</link>.*</item>.*
@Include=UserVariables.inc
FontName=Segoe UI
FontName2=Calibri
TxtColor=255,255,255
TxtColor2=255,255,255,120
ShwColor=0,0,0,100
HideHint=0


Item=(?(?=.*<item>).*<item>.*<title>(.*)</title>.*<link>(.*)</link>.*<pubDate>(.*)</pubDate>)
Sub="^\s+":"","<!\[CDATA\[":"","\]\]>":"","!\[CDATA\[":"","\]\]":""

LastCat=1


[JustDoIt]
Measure=Calc
Formula=1
IfCondition=1=1
IfTrueAction=[!HideMeterGroup Feeds][!ShowMeterGroup #LastCat#][!Update][!Redraw]
DynamicVariables=1


[MeasureSite]
Measure=WebParser
URL=https://#Rss_Link#
RegExp=(?siU)<title>(.*)</title>.*<link>(.*)</link>#Item##Item##Item##Item##Item##Item##Item##Item##Item##Item##Item##Item#
FinishAction=!Update "#CURRENTCONFIG#"

[MeasureSiteTitle]
Measure=WebParser
URL=[MeasureSite]
StringIndex=1
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[1Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=3
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[1Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=4

[1Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=5
Substitute=",":""

;Item 2 info

[2Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=6
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[2Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=7

[2Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=8
Substitute=",":""
;Item 3 info

[3Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=9
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[3Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=10

[3Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=11
Substitute=",":""
;Item 4 info

[4Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=12
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[4Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=13

[4Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=14
Substitute=",":""
;Item 5 info

[5Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=15
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[5Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=16

[5Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=17
Substitute=",":""
;Item 5 info

[6Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=18
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[6Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=19

[6Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=20
Substitute=",":""
;Item 5 info

[7Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=21
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[7Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=22

[7Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=23
Substitute=",":""
;Item 5 info

[8Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=24
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[8Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=25

[8Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=26
Substitute=",":""

;Item 5 info

[9Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=27
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[9Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=28
[9Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=29
Substitute=",":""
;Item 5 info

[10Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=30
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[10Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=31

[10Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=32
Substitute=",":""
;Item 5 info

[11Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=33
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[11Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=34

[11Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=35
Substitute=",":""

;Item 5 info

[12Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=36
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[12Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=37

[12Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=38
Substitute=",":""

[TitleStyle]
W=60
H=15
Y=R
X=5
FontColor=#TxtColor2#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
ClipString=1
MeasureName=MeasureSiteTitle


[DateStyle]
X=68
W=55
H=15
Y=r
FontColor=#TxtColor2#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
ClipString=1


[RSSStyle]
W=120
H=15
Y=4R
X=5
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
ClipString=1
ToolTipText=%1

[Feeds]
Group=Feeds
Hidden=1


[1]
Group=1
Hidden=0

[2]
Group=2
Hidden=1

[3]
Group=3
Hidden=1
###





[RSS1]
MeasureName=1Title
Meter=STRING
Y=5
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[1Link]]

[RSS1Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 1

[RSS1Date]
MeasureName=1Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 1

[RSS2]
MeasureName=2Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[2Link]]

[RSS2Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 1

[RSS2Date]
MeasureName=2Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 1

[RSS3]
MeasureName=3Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[3Link]]

[RSS3Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 1

[RSS3Date]
MeasureName=3Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 1

[RSS4]
MeasureName=4Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[4Link]]

[RSS4Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 1

[RSS4Date]
MeasureName=4Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 1

##


[RSS5]
MeasureName=5Title
Meter=STRING
Y=5
MeterStyle=RSSStyle | Feeds | 2
LeftMouseUpAction=!Execute [[5Link]]

[RSS5Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 2

[RSS5Date]
MeasureName=5Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 2

[RSS6]
MeasureName=6Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 2
LeftMouseUpAction=!Execute [[6Link]]

[RSS6Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 2

[RSS6Date]
MeasureName=6Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 2

[RSS7]
MeasureName=7Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 2
LeftMouseUpAction=!Execute [[7Link]]

[RSS7Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 2

[RSS7Date]
MeasureName=7Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 2

[RSS8]
MeasureName=7Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 2
LeftMouseUpAction=!Execute [[8Link]]

[RSS8Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 2

[RSS8Date]
MeasureName=8Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 2

[RSS9]
MeasureName=9Title
Meter=STRING
Y=5
MeterStyle=RSSStyle | Feeds | 3
LeftMouseUpAction=!Execute [[9Link]]

[RSS9Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 3

[RSS9Date]
MeasureName=9Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 3

[RSS10]
MeasureName=10Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 3
LeftMouseUpAction=!Execute [[10Link]]

[RSS10Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 3

[RSS10Date]
MeasureName=10Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 3

[RSS11]
MeasureName=11Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 3
LeftMouseUpAction=!Execute [[11Link]]

[RSS11Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 3

[RSS11Date]
MeasureName=11Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 3

[RSS12]
MeasureName=12Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 3
LeftMouseUpAction=!Execute [[12Link]]

[RSS12Title]
Meter=STRING
MeterStyle=TitleStyle | Feeds | 3

[RSS12Date]
MeasureName=12Date
Meter=STRING
MeterStyle=DateStyle | Feeds | 3


[Explorer]
Meter=IMAGE
ImageName=#@#img\Explorer.png
X=26
Y=145

[Up]
Meter=Button
ButtonImage=#@#img\ButtonUp.png
X=28
Y=148
ButtonCommand=!Execute [!HideMeterGroup 2][!HideMeterGroup 1][!ShowMeterGroup 3][!Redraw]
MeterStyle=Feeds | 1


[Down]
Meter=Button
ButtonImage=#@#img\ButtonDown.png
X=86
Y=148
ButtonCommand=!Execute [!HideMeterGroup 3][!HideMeterGroup 1][!ShowMeterGroup 2][!Redraw]
MeterStyle=Feeds | 1


[Up2]
Meter=Button
ButtonImage=#@#img\ButtonUp.png
X=28
Y=148
ButtonCommand=!Execute  [!HideMeterGroup 3][!HideMeterGroup 2][!ShowMeterGroup 1][!Redraw]
MeterStyle=Feeds | 2

[Down2]
Meter=Button
ButtonImage=#@#img\ButtonDown.png
X=86
Y=148
ButtonCommand=!Execute [!HideMeterGroup 1][!HideMeterGroup 2][!ShowMeterGroup 3][!Redraw]
MeterStyle=Feeds | 2

[Up3]
Meter=Button
ButtonImage=#@#img\ButtonUp.png
X=28
Y=148
ButtonCommand=!Execute [!HideMeterGroup 1][!HideMeterGroup 3][!ShowMeterGroup 2][!Redraw]
MeterStyle=Feeds | 3

[Down3]
Meter=Button
ButtonImage=#@#img\ButtonDown.png
X=86
Y=148
ButtonCommand=!Execute [!HideMeterGroup 2][!HideMeterGroup 3][!ShowMeterGroup 1][!Redraw]
MeterStyle=Feeds | 3


[Num]
Meter=STRING
X=65
Y=147
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=10
StringAlign=CENTER
FontFace=#FontName2#
AntiAlias=1
Text=1-4
Group=1

[Num2]
Meter=STRING
X=65
Y=147
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=10
StringAlign=CENTER
FontFace=#FontName2#
AntiAlias=1
Text=4-8
Hidden=1
Group=2

[Num3]
Meter=STRING
X=65
Y=147
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=10
StringAlign=CENTER
FontFace=#FontName2#
AntiAlias=1
Text=8-12
Hidden=1
Group=3

###


[HintBg]
Meter=IMAGE
ImageName=Headlines.png
x=3
y=3
Hidden=#HideHint#
LeftMouseUpAction=!execute [!WriteKeyValue Variables HideHint 1][!HideMeter HintBg][!Redraw]
MouseActionCursor=1 

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXPS.png
X=118
Y=0
Hidden=1


[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Plus]
Meter=BUTTON
ButtonImage=#@#img\Plus.png
X=118
Y=21
ButtonCommand=!Execute [!ActivateConfig "Vista Rainbar\RSS\1" "1+.ini"][!RainmeterRefresh]
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=42
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1

