[Metadata]
Name=Buy RED Gadget | Style 1
Config=Vista Rainbar | Clock | RED
Description=Display the time in analog form.
Version=5.0
Tags=Gadget | Vista Rainbar | Clock | Time
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=-1

[Variables]
@include=UserVariables.inc

[img]
Meter=IMAGE
w=125
h=54
ImageName=Red.png
LeftMouseUpAction=!execute ["#Link#"]
MouseActionCursor=1 

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=137
h=140
MouseOverAction=!execute [!ShowMeter More][!ShowMeter Menu][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter More][!HideMeter Menu][!HideMeter Close][!Redraw]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=120
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=120
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1


[More]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=120
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1
