[Metadata]
Name=Gallery Window | Disk
Config=Vista Rainbar | Gallery | Window
Description=Allows easy access to the Vista Rainbar gadgets.
Version=5.0
Tags=Gadget | Vista Rainbar | Gallery
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Window.png

[Variables]
Disk1=C:
Disk2=D:
Disk3=E:
Disk4=F:
Disk5=G:
Disk6=H:
@include=..\..\Disk\settings.inc
FontName=Segoe UI
TxtColor=255,255,255
ShwColor=0,0,0

###

[Txt]
Meter=STRING
X=30
Y=30
FontColor=#ShwColor#
FontSize=9
StringAlign=LEFT
StringStyle=BOLD
FontFace=#FontName#
Antialias=1
Text=Please select gadget to open

[Txt2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=9
StringAlign=LEFT
StringStyle=BOLD
FontFace=#FontName#
Antialias=1
Text=Please select gadget to open

[Button]
Meter=BUTTON
ButtonImage=OK.png
X=284
Y=258
ButtonCommand=!RainmeterDeactivateConfig

[Close]
Meter=STRING
X=321
Y=259
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Close

[Button2]
Meter=BUTTON
ButtonImage=OK.png
X=194
Y=258
ButtonCommand=!Execute ["#SKINSPATH#Vista Rainbar\Disk\DiskConfig.exe"]

[Config]
Meter=STRING
X=231
Y=259
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Configure

[Rainbar]
Meter=STRING
X=41
Y=259
FontColor=0,0,0,180
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Vista Rainbar 4.6

###

[A1]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=50
Y=68
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Disk\1" "1.ini"

[IcoA1]
Meter=IMAGE
ImageName=Disque2.png
X=50
Y=68

[A2]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=155
Y=68
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Disk\2" "1.ini"

[IcoA2]
Meter=IMAGE
ImageName=Disque.png
X=155
Y=68

[A3]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=260
Y=68
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Disk\3" "1.ini"

[IcoA3]
Meter=IMAGE
ImageName=Disque.png
X=260
Y=68

[B1]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=50
Y=159
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Disk\4" "1.ini"

[IcoB1]
Meter=IMAGE
ImageName=Disque.png
X=50
Y=159

[B2]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=155
Y=159
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Disk\5" "1.ini"

[IcoB2]
Meter=IMAGE
ImageName=Disque.png
X=155
Y=159

[B3]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=260
Y=159
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Disk\6" "1.ini"

[IcoB3]
Meter=IMAGE
ImageName=Disque.png
X=260
Y=159

###
-------
[TxtA]
Meter=STRING
X=94
Y=122
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=#Disk1#

[TxtB]
Meter=STRING
X=199
Y=122
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=#Disk2#

[TxtC]
Meter=STRING
X=304
Y=122
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=#Disk3#

[TxtD]
Meter=STRING
X=94
Y=212
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=#Disk4#

[TxtE]
Meter=STRING
X=199
Y=212
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=#Disk5#

[TxtF]
Meter=STRING
X=304
Y=212
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=#Disk6#