[Metadata]
Name=Gallery Window | RED Calendar
Config=Vista Rainbar | Gallery | Window
Description=Allows easy access to the Vista Rainbar gadgets.
Version=5.0
Tags=Gadget | Vista Rainbar | Gallery
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Window.png

[Variables]
FontName=Segoe UI
TxtColor=255,255,255
ShwColor=0,0,0

###

[Txt]
Meter=STRING
X=30
Y=30
FontColor=#ShwColor#
FontSize=9
StringAlign=LEFT
StringStyle=BOLD
FontFace=#FontName#
Antialias=1
Text=Please select gadget to open

[Txt2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=9
StringAlign=LEFT
StringStyle=BOLD
FontFace=#FontName#
Antialias=1
Text=Please select gadget to open

[Button]
Meter=BUTTON
ButtonImage=OK.png
X=284
Y=258
ButtonCommand=!RainmeterDeactivateConfig

[Close]
Meter=STRING
X=321
Y=259
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Exit

[Rainbar]
Meter=STRING
X=41
Y=259
FontColor=0,0,0,180
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Vista Rainbar 4.6

###

[A]
Meter=BUTTON
ButtonImage=Button.png
X=70
Y=100
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Calendar\RED Monday" "Day.ini"

[IconA]
Meter=IMAGE
ImageName=Monday.png
X=0r
Y=3r

[TxtA]
Meter=STRING
X=53r
Y=81r
W=86
H=18
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RED Monday

###
-----------
[B]
Meter=BUTTON
ButtonImage=Button.png
X=212
Y=100
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Calendar\RED Sunday" "Day.ini"

[IcoB]
Meter=IMAGE
ImageName=Sunday.png
X=0r
Y=3r

[TxtB]
Meter=STRING
X=53r
Y=81r
W=86
H=18
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RED Sunday
