[Metadata]
Name=Gallery Window | RSS
Config=Vista Rainbar | Gallery | Window
Description=Allows easy access to the Vista Rainbar gadgets.
Version=5.0
Tags=Gadget | Vista Rainbar | Gallery
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Window.png

[Variables]
FontName=Segoe UI
TxtColor=255,255,255
ShwColor=0,0,0

###

[TxtS]
Meter=STRING
X=30
Y=30
FontColor=#ShwColor#
FontSize=9
StringAlign=LEFT
StringStyle=BOLD
FontFace=#FontName#
Antialias=1
Text=Please select gadget to open

[TxtS2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=9
StringAlign=LEFT
StringStyle=BOLD
FontFace=#FontName#
Antialias=1
Text=Please select gadget to open

[Button]
Meter=BUTTON
ButtonImage=OK.png
X=284
Y=258
ButtonCommand=!RainmeterDeactivateConfig

[Close]
Meter=STRING
X=321
Y=259
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Close

[Button2]
Meter=BUTTON
ButtonImage=OK.png
X=194
Y=258
ButtonCommand=!Execute ["#SKINSPATH#Vista Rainbar\RSS\RSSConfig.exe"]

[Config]
Meter=STRING
X=231
Y=259
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Configure

[Rainbar]
Meter=STRING
X=41
Y=259
FontColor=0,0,0,180
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Vista Rainbar 4.6

###

[1]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=50
Y=113
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\RSS\1" "1.ini"

[Ico1]
Meter=IMAGE
ImageName=RSS.png
X=0r
Y=3r

[Txt1]
Meter=STRING
X=44r
Y=62r
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RSS 1

[2]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=155
Y=113
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\RSS\2" "1.ini"

[Ico2]
Meter=IMAGE
ImageName=RSS.png
X=0r
Y=3r

[Txt2]
Meter=STRING
X=44r
Y=62r
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RSS 2

[3]
Meter=BUTTON
ButtonImage=ButtonBlue.png
X=260
Y=113
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\RSS\3" "1.ini"

[Ico3]
Meter=IMAGE
ImageName=RSS.png
X=0r
Y=3r

[Txt3]
Meter=STRING
X=44r
Y=62r
W=86
H=32
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=ITALIC
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RRS 3
