[Metadata]
Name=Analog Clock Gadget | Antique
Config=Vista Rainbar | Clock | Normal
Description=Display the time in analog form. 
Version=5.0
Tags=Gadget | Vista Rainbar | Clock | Time
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png



[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=#Show_Seconds#000

[img]
Meter=IMAGE
w=130
h=130
ImageName=#Clock_Style#.png

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=140
h=140
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Close][!ShowMeter Plus][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Close][!HideMeter Plus][!Redraw]

[Variables]
@Include2=UserVariables.inc
Launch=0

[MeasureTime]
Measure=Time
Timezone=#Time_zone#
[1]
Measure=Time
Format=%H:%M:%S

[2]
Measure=Time
Format=%I:%M %p

[3]
Measure= Plugin
Plugin=Plugins\SysInfo.dll
SysInfoType=HOST_NAME

[4]
Measure=Time
Format=%Z

###

[Txt]
Meter=STRING
Text=#Clock_name#
X=64
Y=72
H=16
W=64
FontFace=Segoe UI
FontColor=51,50,49
FontSize=9
StringAlign=CENTER
StringStyle=BOLD
Antialias=1
Clipstring=1

[HoursShw]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=HoursShw#Clock_Style#.png
X=65
Y=65
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=43200
OffsetX=6
OffsetY=64

[Hours]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=Hours#Clock_Style#.png
X=63
Y=63
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=43200
OffsetX=6
OffsetY=64

[MinutesShw]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=minuteShw#Clock_Style#.png
X=65
Y=65
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=3600
OffsetX=6
OffsetY=64

[Minutes]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=minute#Clock_Style#.png
X=63
Y=63
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=3600
OffsetX=6
OffsetY=64

[Point]
Meter=IMAGE
ImageName=point#Clock_Style#.png
X=58
Y=-1

[SecondesShw]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=secShw#Clock_Style##Show_Seconds#.png
X=65
Y=65
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=60
OffsetX=6
OffsetY=64

[Secondes]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=seconde#Clock_Style##Show_Seconds#.png
X=63
Y=63
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=60
OffsetX=6
OffsetY=64

[Glass]
Meter=IMAGE
ImageName=glassAntic.png
X=0
Y=0

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=0

[Plus]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"][!WriteKeyValue Variables Launch 0]
Hidden=1
