[Metadata]
Name=Wireless Gadget | Style 4
Config=Vista Rainbar | Wireless
Description=Displays the wireless network strength.
Version=5.0
Tags=Gadget | Vista Rainbar | RSS | Feed
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
Author=legace@inbox.com

Background=ClearGlass.png
MouseActionCursor=0
Update=2500
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Back][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Back][!HideMeter Close][!Redraw]

[Variables]
FontName=Segoe UI
FontName2=Microsoft Sans Serif
TxtColor=255,255,255,200
ShwColor=0,0,0,200

###

[MeasureStrength]
Measure=Plugin
Plugin=Plugins\WifiStatus.dll
WifiInfoType=QUALITY
IfAboveValue=0
IfAboveAction=!execute [!HideMeter VU2][!ShowMeter VU][!ShowMeter Protected][!ShowMeter Percent][!ShowMeter Percent2][!Redraw]
IfBelowValue=1
IfBelowAction=!execute [!ShowMeter VU2][!HideMeter VU][!HideMeter Protected][!HideMeter Percent][!HideMeter Percent2][!Redraw]
WifiIntfID=0

[MeasureSSID]
Measure=Plugin
Plugin=Plugins\WifiStatus.dll
WifiInfoType=SSID
WifiIntfID=0
Substitute="-1":"Disconnected"

[MeasureEncryption]
Measure=Plugin
Plugin=Plugins\WifiStatus.dll
WifiInfoType=ENCRYPTION
WifiIntfID=0
Substitute="WEP40":"Lock","TKIP":"Lock","AES":"Lock","WEP104":"Lock","WPA_GROUP":"Lock","WEP":"Lock"

###

[VU]
Meter=BITMAP
MeasureName=MeasureStrength
X=8
Y=9
BitmapImage=SignalLevelOn.png
BitmapFrames=5
BitmapZeroFrame=1
Hidden=1

[VU2]
Meter=Image
ImageName=SignalLevelOff.png
X=8
Y=9

[Protected]
Meter=IMAGE
MeasureName=MeasureEncryption
X=38
Y=33

[Percent]
Meter=STRING
MeasureName=MeasureStrength
X=89
Y=15
FontColor=#ShwColor#
FontFace=#FontName#
FontSize=12
StringAlign=CENTER
StringStyle=BOLD
AntiAlias=1
Postfix=%
Hidden=1

[Percent2]
Meter=STRING
MeasureName=MeasureStrength
X=1r
Y=-1r
FontColor=#TxtColor#
FontFace=#FontName#
FontSize=12
StringAlign=CENTER
StringStyle=BOLD
AntiAlias=1
Postfix=%
Hidden=1

[SSID]
Meter=STRING
MeasureName=MeasureSSID
X=88
Y=36
W=68
H=12
FontColor=#ShwColor#
FontFace=Calibri
FontSize=8
StringAlign=CENTER
StringStyle=BOLD
AntiAlias=1
ClipString=1

[SSID2]
Meter=STRING
MeasureName=MeasureSSID
X=1r
Y=-1r
W=68
H=12
FontColor=#TxtColor#
FontFace=Calibri
FontSize=8
StringAlign=CENTER
StringStyle=BOLD
AntiAlias=1
ClipString=1

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXRL.png
X=130
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=130
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=130
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Wireless" "1.ini"
Hidden=1

[Back]
Meter=BUTTON
ButtonImage=#@#img\Back.png
X=130
Y=42
ButtonCommand=!ActivateConfig "Vista Rainbar\Wireless" "3.ini"
Hidden=1
