[Metadata]
Name=Recycle Bin Gadget | Style 2
Config=Vista Rainbar | Recycle Bin
Description=A recycle bin gadget.
Instructions=Configure the drives being watched for trash through the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Recycle Bin
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

ContextTitle=Settings
ContextAction=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
ContextTitle2=Close
ContextAction2=!DeactivateConfig
ContextTitle3=Empty Recycle Bin
ContextAction3=!ActivateConfig "#currentconfig#"
ContextTitle4=----
ContextAction4=[]
ContextTitle5=More Actions
ContextAction5=[!SkinMenu]


[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=145
h=100
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter empty_button][!ShowMeter Set][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter empty_button][!HideMeter Set][!HideMeter Close][!Redraw]
BackgroundMode=1
Update=5000
UpdateDivider=10

[Variables]
Drives=C:|
@Include=UserVariables.inc
Launch=0

###

[MeasureBin]
Measure=Plugin
Plugin=RecycleManager.dll
RecycleType=COUNT
Drives=#Drives#

###

[BinEmpty]
Meter=IMAGE
ImageName=#currentpath#beta2\#Bin_Style#\#Bin_Style#_default.png
W=130
H=90
Hidden=0
LeftMouseUpAction=!RainmeterPluginBang "MeasureBin OpenBin"

MouseActionCursor=0

[BinFull]
Meter=IMAGE
ImageName=#currentpath#beta2\#Bin_Style#\#Bin_Style#_default_full.png
W=130
H=90
Hidden=1
LeftMouseUpAction=!RainmeterPluginBang "MeasureBin OpenBin"
MouseActionCursor=0

[BinAction]
Measure=Calc
Formula=MeasureBin
IfAboveAction=!execute [!HideMeter BinEmpty][!ShowMeter BinFull]
IfAboveValue=0
IfEqualAction=!execute [!HideMeter BinFull][!ShowMeter BinEmpty]
IfEqualValue=0


[empty_button]
Meter=IMAGE
ImageName=#currentpath#emptyButt_on.png
Hidden=1
y=40
LeftMouseUpAction=!RainmeterPluginBang "MeasureBin EmptyBin"
MouseActionCursor=1
###

[Close]
Meter=BUTTON
ButtonImage=#@#\Graphics\Sidebar\Dropdown.png
X=130
Y=0
ButtonCommand=!SkinCustomMenu
Hidden=1