[Metadata]
Name=Power Gadget | Options Dialog
Config=Vista Rainbar | Power | Options
Description=Allows you to to shutdown, reboot, logout, or sleep.
Version=5.0
Tags=Gadget | Vista Rainbar | System | Power
License=Creative Commons Attribution-Noncommercial-No Derivative Works 3.0

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=options.png

[Variables]
FontName=Segoe UI
TxtColor=255,255,255
Shw_Color=0,0,0

Action1='"#ADDONSPATH#nircmd\nircmd.exe" exitwin poweroff'
Action2='"#ADDONSPATH#nircmd\nircmd.exe" exitwin reboot'
Action3='"#ADDONSPATH#nircmd\nircmd.exe" hibernate'
Action4='"#ADDONSPATH#nircmd\nircmd.exe" exitwin logoff'

###

[MeterImage]
Meter=BUTTON
ButtonImage=..\shutdownbutton.png
X=90
Y=60
ButtonCommand=!execute [#Action1#][!RainmeterDeactivateConfig]

[MeterTxtShw]
Meter=STRING
X=106
Y=98
FontColor=#Shw_Color#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Shutdown

[MeterTxt]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Shutdown

[MeterImage2]
Meter=BUTTON
ButtonImage=..\restartbutton.png
X=238
Y=60
ButtonCommand=!execute [#Action2#][!RainmeterDeactivateConfig]

[MeterTxt2Shw]
Meter=STRING
X=254
Y=98
FontColor=#Shw_Color#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Restart

[MeterTxt2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Restart

[MeterImage3]
Meter=BUTTON
ButtonImage=..\sleepbutton.png
X=90
Y=140
ButtonCommand=!execute [#Action3#][!RainmeterDeactivateConfig]

[MeterTxt3Shw]
Meter=STRING
X=106
Y=178
FontColor=#Shw_Color#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Sleep

[MeterTxt3]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Sleep

[MeterImage4]
Meter=BUTTON
ButtonImage=..\logoffbutton.png
X=238
Y=140
ButtonCommand=!execute [#Action4#][!RainmeterDeactivateConfig]

[MeterTxt4Shw]
Meter=STRING
X=254
Y=178
FontColor=#Shw_Color#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Logout

[MeterTxt4]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Logout

###

[MeterClose]
Meter=BUTTON
ButtonImage=..\..\Gallery\Window\OK.png
X=143
Y=222
ButtonCommand=!RainmeterDeactivateConfig

[MeterCancel]
Meter=STRING
X=180
Y=223
FontColor=#Shw_Color#
StringStyle=NORMAL
FontSize=9
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Text=Cancel

