[Metadata]
Name=Power Gadget | Style 2
Config=Vista Rainbar | Power
Description=A gadget to shutdown, reboot, or sleep your computer.
Version=5.0
Tags=Gadget | Vista Rainbar | System | Power
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=1000
UpdateDivider=180


[img]
Meter=IMAGE
imagename=Background.png

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=138
h=100
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
FontName=Segoe UI
TxtColor=220,220,220
ShwColor=0,0,0

Action1='"#ADDONSPATH#nircmd\nircmd.exe" exitwin poweroff'

[MeasureUptime]
Measure=Uptime
Substitute="d":"d",":":"h ","00":"0","01":"1","02":"2","03":"3","04":"4","05":"5","06":"6","07":"7","08":"8","09":"9"

###

[UptimeShw]
MeasureName=MeasureUptime
Meter=STRING
X=64
Y=14
FontColor=#ShwColor#
FontSize=9
FontFace=#FontName#
StringStyle=BOLD
StringAlign=CENTER
AntiAlias=1
Text=%1 min

[Uptime]
MeasureName=MeasureUptime
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=9
FontFace=#FontName#
StringStyle=BOLD
StringAlign=CENTER
AntiAlias=1
Text=%1 min

[Shutdown]
Meter=BUTTON
ButtonImage=shutdown.png
X=19
Y=36
ButtonCommand=!Execute [#Action1#]

[Arrow]
Meter=BUTTON
ButtonImage=arrow.png
X=70r
Y=0r
ButtonCommand=!ActivateConfig "Vista Rainbar\Power\Options" "Options.ini"

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=118
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Power" "2.ini"
Hidden=1
