[Metadata]
Name=App Launcher Gadget | Style 3
Config=Vista Rainbar | Launcher
Description=Shows shortcuts to applications for quick launching. | This style has 2 rows and 2 columns.
Instructions=Set your preferred applications using the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Launcher
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=-1
[img]
Meter=IMAGE
imagename=Lanceur4.png

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=138
h=130
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Set][!ShowMeter More][!ShowMeter Back][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Set][!HideMeter More][!HideMeter Back][!HideMeter Close][!Redraw]

[Variables]
@Include=UserVariables.inc

###

[Img_Soft1]
Meter=IMAGE
ImageName=#Soft1.icon#
X=8
Y=8
W=50
H=50

[ME_Soft1]
Meter=IMAGE
X=2r
Y=2r
W=50
H=50

LeftMouseUpAction=!execute ["#Soft1#"]

[Img_Soft2]
Meter=IMAGE
ImageName=#Soft2.icon#
X=70
Y=8
W=50
H=50

[ME_Soft2]
Meter=IMAGE
X=2r
Y=2r
W=50
H=50

LeftMouseUpAction=!execute ["#Soft2#"]

[Img_Soft3]
Meter=IMAGE
ImageName=#Soft3.icon#
X=8
Y=70
W=50
H=50

[ME_Soft3]
Meter=IMAGE
X=2r
Y=2r
W=50
H=50

LeftMouseUpAction=!execute ["#Soft3#"]

[Img_Soft4]
Meter=IMAGE
ImageName=#Soft4.icon#
X=70
Y=70
W=50
H=50

[ME_Soft4]
Meter=IMAGE
X=2r
Y=2r
W=50
H=50

LeftMouseUpAction=!execute ["#Soft4#"]

###



###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1
