[Metadata]
Name=App Launcher Gadget | Style 2
Config=Vista Rainbar | Launcher
Description=Shows shortcuts to applications for quick launching. | This style has 1 row and 3 columns.
Instructions=Set your preferred applications using the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Launcher
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Lanceur3.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Set][!ShowMeter More][!ShowMeter Back][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Set][!HideMeter More][!HideMeter Back][!HideMeter Close][!Redraw]

[Variables]
Soft1.icon=Soft1.png
Soft1=explorer.exe /root,,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Soft2.icon=Soft2.png
Soft2=notepad.exe
Soft3.icon=Soft3.png
Soft3=firefox.exe
Soft4.icon=Soft4.png
Soft4=mspaint.exe
Soft5.icon=Soft5.png
Soft5=calc.exe
Soft6.icon=Soft6.png
Soft6=wmplayer.exe
@Include=settings.inc

###

[Img_Soft1]
Meter=IMAGE
ImageName=#Soft1.icon#
X=8
Y=6
W=32
H=32

[ME_Soft1]
Meter=IMAGE
X=2r
Y=2r
W=30
H=30
MouseOverAction=!execute [!HideMeter Img_Soft1][!ShowMeter hilighthSoft1][!Redraw] 
MouseLeaveAction=!execute [!HideMeter hilighthSoft1][!ShowMeter Img_Soft1][!Redraw] 
LeftMouseUpAction=!execute ["#Soft1#"]

[Img_Soft2]
Meter=IMAGE
ImageName=#Soft2.icon#
X=48
Y=6
W=32
H=32

[ME_Soft2]
Meter=IMAGE
X=2r
Y=2r
W=30
H=30
MouseOverAction=!execute [!HideMeter Img_Soft2][!ShowMeter hilighthSoft2][!Redraw] 
MouseLeaveAction=!execute [!HideMeter hilighthSoft2][!ShowMeter Img_Soft2][!Redraw] 
LeftMouseUpAction=!execute ["#Soft2#"]

[Img_Soft3]
Meter=IMAGE
ImageName=#Soft3.icon#
X=88
Y=6
W=32
H=32

[ME_Soft3]
Meter=IMAGE
X=2r
Y=2r
W=30
H=30
MouseOverAction=!execute [!HideMeter Img_Soft3][!ShowMeter hilighthSoft3][!Redraw] 
MouseLeaveAction=!execute [!HideMeter hilighthSoft3][!ShowMeter Img_Soft3][!Redraw] 
LeftMouseUpAction=!execute ["#Soft3#"]

###

[hilighthSoft1]
Meter=IMAGE
ImageName=#Soft1.icon#
X=6
Y=4
W=36
H=36
hidden=1

[hilighthSoft2]
Meter=IMAGE
ImageName=#Soft2.icon#
X=46
Y=4
W=36
H=36
hidden=1

[hilighthSoft3]
Meter=IMAGE
ImageName=#Soft3.icon#
X=86
Y=4
W=36
H=36
hidden=1


###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXSRL.png
X=130
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=130
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=130
Y=21
ButtonCommand=!Execute ["#CURRENTPATH#LauncherConfig.exe"]
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=130
Y=42
ButtonCommand=!ActivateConfig "Vista Rainbar\Launcher" "3.ini"
Hidden=1

[Back]
Meter=BUTTON
ButtonImage=#@#img\Back.png
X=130
Y=63
ButtonCommand=!ActivateConfig "Vista Rainbar\Launcher" "1.ini"
Hidden=1
