[Metadata]
Name=App Launcher Gadget | Style 3
Config=Vista Rainbar | Launcher
Description=Shows shortcuts to applications for quick launching. | This style has 2 rows and 2 columns.
Instructions=Set your preferred applications using the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Launcher
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=-1
ContextTitle=Settings
ContextAction=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
ContextTitle2=Close
ContextAction2=!DeactivateConfig
ContextTitle3=----
ContextAction3=[]
ContextTitle4=More Actions
ContextAction4=[!SkinMenu]


[img]
Meter=IMAGE
imagename=LauncherGadget.png

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=158
h=130
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Set][!ShowMeter More][!ShowMeter Back][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Set][!HideMeter More][!HideMeter Back][!HideMeter Close][!Redraw]

[Variables]
@Include=UserVariables.inc

###

[Img_Soft1]
Meter=IMAGE
ImageName=#Soft1.icon#
X=10
Y=8
W=64
H=64
LeftMouseUpAction=!execute ["#Soft1#"]

[Img_Soft2]
Meter=IMAGE
ImageName=#Soft2.icon#
X=5R
Y=r
W=64
H=64
LeftMouseUpAction=!execute ["#Soft2#"]



[Img_Soft3]
Meter=IMAGE
ImageName=#Soft3.icon#
X=10
Y=4R
W=64
H=64
LeftMouseUpAction=!execute ["#Soft3#"]

[Img_Soft4]
Meter=IMAGE
ImageName=#Soft4.icon#
X=5R
Y=r
W=64
H=64
LeftMouseUpAction=!execute ["#Soft4#"]

###



###


[Close]
Meter=BUTTON
ButtonImage=#@#\Graphics\Sidebar\Dropdown.png
X=140
Y=5
ButtonCommand=!SkinCustomMenu
Hidden=1
