[Metadata]
Name=Gallery
Config=Vista Rainbar | Gallery
Description=A gallery, which allows easy access to all of the Vista Rainbar gadgets.
Version=5.0
Tags=Vista Rainbar | Gallery
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=GalleryTop.png

[Variables]
FontName=Segoe UI
ShwColor=0,0,0
ShwColor1=0,100,200
ShwColor2=50,50,50

###

[StyleText]
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Clipstring=1

###

[Bottom]
Meter=Image
ImageName=GalleryBottom.png
Y=422

[BottomMore]
Meter=Image
ImageName=GalleryMore.png
Y=422
Hidden=1

[About]
Meter=Image
ImageName=About.png
X=0
Y=426
LeftMouseUpAction=!Execute ["http://poiru.deviant"]
MouseActionCursor=1
Hidden=1

[Txt]
Meter=STRING
X=575
Y=436
FontColor=#ShwColor1#
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Vista Rainbar 4.6
LeftMouseUpAction=!Execute ["http://poiru.deviantart.com/art/Vista-Rainbar-156603886"]
MouseActionCursor=1

[Txt1]
Meter=STRING
X=575
Y=536
FontColor=#ShwColor1#
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Text=Vista Rainbar 4.6
LeftMouseUpAction=!Execute ["http://poiru.deviantart.com/art/Vista-Rainbar-156603886"]
MouseActionCursor=1
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=CloseButton.png
X=642
Y=7
ButtonCommand=!RainmeterDeactivateConfig

[Image]
Meter=BUTTON
ButtonImage=btn.png
X=495
Y=53

[Right]
Meter=IMAGE
ImageName=Right.png
X=139
Y=51
Hidden=1

[Next]
Meter=BUTTON
ButtonImage=NextButton.png
X=139
Y=51
ButtonCommand=!Execute [!HideMeter Explorer][!HideMeter Next][!ShowMeter Explorer2][!ShowMeter Previous][!HideMeter A1][!HideMeter A1Ico][!HideMeter A1Blur][!HideMeter A1Txt][!HideMeter A2][!HideMeter A2Ico][!HideMeter A2Blur][!HideMeter A2Txt][!HideMeter A3][!HideMeter A3Ico][!HideMeter A3Blur][!HideMeter A3Txt][!HideMeter A4][!HideMeter A4Ico][!HideMeter A4Blur][!HideMeter A4Txt][!HideMeter A5][!HideMeter A5Ico][!HideMeter A5Blur][!HideMeter A5Txt][!HideMeter A6][!HideMeter A6Ico][!HideMeter A6Blur][!HideMeter A6Txt][!HideMeter B1][!HideMeter B1Ico][!HideMeter B1Blur][!HideMeter B1Txt][!HideMeter B2][!HideMeter Left][!HideMeter B2Ico][!HideMeter B2Blur][!HideMeter B2Txt][!HideMeter B3][!HideMeter B3Ico][!HideMeter B3Blur][!HideMeter B3Txt][!HideMeter B4][!HideMeter B4Ico][!HideMeter B4Blur][!HideMeter B4Txt][!HideMeter B5][!HideMeter B5Ico][!HideMeter B5Blur][!HideMeter B5Txt][!HideMeter B6][!HideMeter B6Ico][!HideMeter B6Blur][!HideMeter B6Txt][!HideMeter C1][!HideMeter C1Ico][!HideMeter C1Blur][!HideMeter C1Txt][!HideMeter C2][!HideMeter C2Ico][!HideMeter C2Blur][!HideMeter C2Txt][!HideMeter C3][!HideMeter C3Ico][!HideMeter C3Blur][!HideMeter C3Txt][!HideMeter C4][!HideMeter C4Ico][!HideMeter C4Blur][!HideMeter C4Txt][!HideMeter C5][!HideMeter C5Ico][!HideMeter C5Blur][!HideMeter C5Txt][!HideMeter C6][!HideMeter C6Ico][!HideMeter C6Blur][!HideMeter C6Txt][!ShowMeter D1][!ShowMeter D1Ico][!ShowMeter D1Blur][!ShowMeter D1Txt][!ShowMeter D2][!ShowMeter D2Ico][!ShowMeter D2Blur][!ShowMeter D2Txt][!ShowMeter D3][!ShowMeter D3Ico][!ShowMeter D3Blur][!ShowMeter D3Txt][!ShowMeter D4][!ShowMeter D4Ico][!ShowMeter D4Blur][!ShowMeter D4Txt][!ShowMeter Right][!Redraw]

[Left]
Meter=IMAGE
ImageName=Left.png
X=26
Y=51

[Previous]
Meter=BUTTON
ButtonImage=PreviousButton.png
X=26
Y=51
ButtonCommand=!Execute [!ShowMeter Explorer][!ShowMeter Next][!ShowMeter Left][!HideMeter Explorer2][!HideMeter Previous][!ShowMeter A1][!ShowMeter A1Ico][!ShowMeter A1Blur][!ShowMeter A1Txt][!ShowMeter A2][!ShowMeter A2Ico][!ShowMeter A2Blur][!ShowMeter A2Txt][!ShowMeter A3][!ShowMeter A3Ico][!ShowMeter A3Blur][!ShowMeter A3Txt][!ShowMeter A4][!ShowMeter A4Ico][!ShowMeter A4Blur][!ShowMeter A4Txt][!ShowMeter A5][!ShowMeter A5Ico][!ShowMeter A5Blur][!ShowMeter A5Txt][!ShowMeter A6][!ShowMeter A6Ico][!ShowMeter A6Blur][!ShowMeter A6Txt][!ShowMeter B1][!ShowMeter B1Ico][!ShowMeter B1Blur][!ShowMeter B1Txt][!ShowMeter B2][!ShowMeter B2Ico][!ShowMeter B2Blur][!ShowMeter B2Txt][!ShowMeter B3][!ShowMeter B3Ico][!ShowMeter B3Blur][!ShowMeter B3Txt][!ShowMeter B4][!ShowMeter B4Ico][!ShowMeter B4Blur][!ShowMeter B4Txt][!ShowMeter B5][!ShowMeter B5Ico][!ShowMeter B5Blur][!ShowMeter B5Txt][!ShowMeter B6][!ShowMeter B6Ico][!ShowMeter B6Blur][!ShowMeter B6Txt][!ShowMeter C1][!ShowMeter C1Ico][!ShowMeter C1Blur][!ShowMeter C1Txt][!ShowMeter C2][!ShowMeter C2Ico][!ShowMeter C2Blur][!ShowMeter C2Txt][!ShowMeter C3][!ShowMeter C3Ico][!ShowMeter C3Blur][!ShowMeter C3Txt][!ShowMeter C4][!ShowMeter C4Ico][!ShowMeter C4Blur][!ShowMeter C4Txt][!ShowMeter C5][!ShowMeter C5Ico][!ShowMeter C5Blur][!ShowMeter C5Txt][!ShowMeter C6][!ShowMeter C6Ico][!ShowMeter C6Blur][!ShowMeter C6Txt][!HideMeter D1][!HideMeter D1Ico][!HideMeter D1Blur][!HideMeter D1Txt][!HideMeter D2][!HideMeter D2Ico][!HideMeter D2Blur][!HideMeter D2Txt][!HideMeter D3][!HideMeter D3Ico][!HideMeter D3Blur][!HideMeter D3Txt][!HideMeter D4][!HideMeter D4Ico][!HideMeter D4Blur][!HideMeter D4Txt][!HideMeter Right][!Redraw]
Hidden=1

[Txt81]
Meter=STRING
X=498
Y=53
FontColor=#ShwColor2#
FontSize=9
StringAlign=LEFT
StringStyle=ITAlIC
FontFace=#FontName#
Antialias=1
Text=Search all gadgets

[Explorer]
Meter=STRING
X=90
Y=53
MeterStyle=StyleText
Clipstring=0
Text=Page 1 of 2

[Explorer2]
Meter=STRING
X=90
Y=53
MeterStyle=StyleText
Clipstring=0
Text=Page 2 of 2
Hidden=1

#################### L I N E   1 ########################

[A1]
Meter=BUTTON
ButtonImage=Button.png
X=29
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Battery" "1.ini"

[A1Ico]
Meter=IMAGE
ImageName=Battery.png
X=29
Y=87

[A1Blur]
Meter=IMAGE
ImageName=Blur.png
X=55
Y=167
H=20
W=54

[A1Txt]
Meter=STRING
X=82
Y=168
H=18
W=100
MeterStyle=StyleText
Text=Battery

###

[A2]
Meter=BUTTON
ButtonImage=Button.png
X=139
Y=84
ButtonCommand=!ActivateConfig "Vista Rainbar\Gallery\Window" "Calendar.ini"

[A2Ico]
Meter=IMAGE
ImageName=Calendar.png
X=139
Y=87

[A2Blur]
Meter=IMAGE
ImageName=Blur.png
X=161
Y=167
H=20
W=62

[A2Txt]
Meter=STRING
X=192
Y=168
H=18
W=100
MeterStyle=StyleText
Text=Calendar

###

[A3]
Meter=BUTTON
ButtonImage=Button.png
X=249
Y=84
ButtonCommand=!ActivateConfig "Vista Rainbar\Gallery\Window" "Clocks.ini"

[A3Ico]
Meter=IMAGE
ImageName=Clock.png
X=249
Y=87

[A3Blur]
Meter=IMAGE
ImageName=Blur.png
X=281
Y=167
H=20
W=42

[A3Txt]
Meter=STRING
X=302
Y=168
H=18
W=100
MeterStyle=StyleText
Text=Clock

###

[A4]
Meter=BUTTON
ButtonImage=Button.png
X=359
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\CPU Meter" "1.ini"

[A4Ico]
Meter=IMAGE
ImageName=CPUMeter.png
X=359
Y=87

[A4Blur]
Meter=IMAGE
ImageName=Blur.png
X=375
Y=167
H=20
W=74

[A4Txt]
Meter=STRING
X=412
Y=168
H=18
W=100
MeterStyle=StyleText
Text=CPU Meter

###

[A5]
Meter=BUTTON
ButtonImage=Button.png
X=469
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Date" "1.ini"

[A5Ico]
Meter=IMAGE
ImageName=Date.png
X=469
Y=87

[A5Blur]
Meter=IMAGE
ImageName=Blur.png
X=502
Y=167
H=20
W=40

[A5Txt]
Meter=STRING
X=522
Y=168
H=18
W=100
MeterStyle=StyleText
Text=Date

###

[A6]
Meter=BUTTON
ButtonImage=Button.png
X=579
Y=84
ButtonCommand=!ActivateConfig "Vista Rainbar\Gallery\Window" "Disk.ini"

[A6Ico]
Meter=IMAGE
ImageName=Drive.png
X=579
Y=87

[A6Blur]
Meter=IMAGE
ImageName=Blur.png
X=598
Y=167
H=20
W=68

[A6Txt]
Meter=STRING
X=632
Y=168
H=18
W=100
MeterStyle=StyleText
Text=Drive Info

#################### L I N E   2 ########################

[B1]
Meter=BUTTON
ButtonImage=Button.png
X=29
Y=196
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Launcher" "1.ini"

[B1Ico]
Meter=IMAGE
ImageName=Launcher.png
X=29
Y=199

[B1Blur]
Meter=IMAGE
ImageName=Blur.png
X=48
Y=279
H=20
W=68

[B1Txt]
Meter=STRING
X=82
Y=280
H=18
W=100
MeterStyle=StyleText
Text=Launcher

###

[B2]
Meter=BUTTON
ButtonImage=Button.png
X=139
Y=196
ButtonCommand=!ActivateConfig "Vista Rainbar\Mail\Gmail" "1.ini"

[B2Ico]
Meter=IMAGE
ImageName=Mail.png
X=139
Y=199

[B2Blur]
Meter=IMAGE
ImageName=Blur.png
X=171
Y=279
H=20
W=42

[B2Txt]
Meter=STRING
X=192
Y=280
H=18
W=100
MeterStyle=StyleText
Text=Gmail

###

[B3]
Meter=BUTTON
ButtonImage=Button.png
X=249
Y=196
ButtonCommand=!ActivateConfig "Vista Rainbar\Gallery\Window" "Media Player.ini"

[B3Ico]
Meter=IMAGE
ImageName=Media Player.png
X=249
Y=199

[B3Blur]
Meter=IMAGE
ImageName=Blur.png
X=258
Y=279
H=20
W=86

[B3Txt]
Meter=STRING
X=302
Y=280
H=18
W=100
MeterStyle=StyleText
Text=Media Player

###

[B4]
Meter=BUTTON
ButtonImage=Button.png
X=359
Y=196
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Multi-Meter" "Black.ini"

[B4Ico]
Meter=IMAGE
ImageName=MultiMeter.png
X=359
Y=199

[B4Blur]
Meter=IMAGE
ImageName=Blur.png
X=370
Y=279
H=20
W=82

[B4Txt]
Meter=STRING
X=411
Y=280
H=18
W=100
MeterStyle=StyleText
Text=Multi-Meter

###

[B5]
Meter=BUTTON
ButtonImage=Button.png
X=469
Y=196
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Network" "1.ini"

[B5Ico]
Meter=IMAGE
ImageName=Network.png
X=469
Y=199

[B5Blur]
Meter=IMAGE
ImageName=Blur.png
X=491
Y=279
H=20
W=62

[B5Txt]
Meter=STRING
X=521
Y=280
H=18
W=100
MeterStyle=StyleText
Text=Network

###

[B6]
Meter=BUTTON
ButtonImage=Button.png
X=579
Y=196
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Power" "1.ini"

[B6Ico]
Meter=IMAGE
ImageName=Uptime.png
X=579
Y=199

[B6Blur]
Meter=IMAGE
ImageName=Blur.png
X=608
Y=279
H=20
W=43

[B6Txt]
Meter=STRING
X=631
Y=280
H=18
W=100
MeterStyle=StyleText
Text=Power

#################### L I N E   3 ########################

[C1]
Meter=BUTTON
ButtonImage=Button.png
X=29
Y=309
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Recycle Bin" "1.ini"

[C1Ico]
Meter=IMAGE
ImageName=Recycle Bin.png
X=29
Y=312

[C1Blur]
Meter=IMAGE
ImageName=Blur.png
X=42
Y=392
H=20
W=80

[C1Txt]
Meter=STRING
X=82
Y=393
H=18
W=100
MeterStyle=StyleText
Text=Recycle Bin

###

[C2]
Meter=BUTTON
ButtonImage=Button.png
X=139
Y=309
ButtonCommand=!ActivateConfig "Vista Rainbar\Gallery\Window" "RSS.ini"

[C2Ico]
Meter=IMAGE
ImageName=RSS.png
X=139
Y=312

[C2Blur]
Meter=IMAGE
ImageName=Blur.png
X=153
X=153
Y=392
H=20
W=78

[C2Txt]
Meter=STRING
X=192
Y=393
H=18
W=100
MeterStyle=StyleText
Text=RSS Feeder

###

[C3]
Meter=BUTTON
ButtonImage=Button.png
X=249
Y=309
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Sidebar" "Fade (Default).ini"

[C3Ico]
Meter=IMAGE
ImageName=Sidebar.png
X=249
Y=312

[C3Blur]
Meter=IMAGE
ImageName=Blur.png
X=274
Y=392
H=20
W=56

[C3Txt]
Meter=STRING
X=302
Y=393
H=18
W=100
MeterStyle=StyleText
Text=Sidebar

###

[C4]
Meter=BUTTON
ButtonImage=Button.png
X=359
Y=309
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Slideshow" "Normal.ini"

[C4Ico]
Meter=IMAGE
ImageName=Slideshow.png
X=359
Y=312

[C4Blur]
Meter=IMAGE
ImageName=Blur.png
X=377
Y=392
H=20
W=69

[C4Txt]
Meter=STRING
X=412
Y=393
H=18
W=100
MeterStyle=StyleText
Text=Slideshow

###

[C5]
Meter=BUTTON
ButtonImage=Button.png
X=469
Y=309
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Sticky Notes" "Yellow.ini"

[C5Ico]
Meter=IMAGE
ImageName=Sticky.png
X=469
Y=312

[C5Blur]
Meter=IMAGE
ImageName=Blur.png
X=479
Y=392
H=20
W=84

[C5Txt]
Meter=STRING
X=521
Y=393
H=18
W=100
MeterStyle=StyleText
Text=Sticky Notes

###

[C6]
Meter=BUTTON
ButtonImage=Button.png
X=579
Y=309
ButtonCommand=!ActivateConfig "Vista Rainbar\Gallery\Window" "Weather.ini"

[C6Ico]
Meter=IMAGE
ImageName=Weather.png
X=579
Y=312

[C6Blur]
Meter=IMAGE
ImageName=Blur.png
X=602
Y=392
H=20
W=58

[C6Txt]
Meter=STRING
X=631
Y=393
H=18
W=100
MeterStyle=StyleText
Text=Weather

#################### L I N E   4 ########################

[D1]
Meter=BUTTON
ButtonImage=Button.png
X=29
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Wireless" "1.ini"
Hidden=1

[D1Ico]
Meter=IMAGE
ImageName=Wireless.png
X=29
Y=87
Hidden=1

[D1Blur]
Meter=IMAGE
ImageName=Blur.png
X=51
Y=167
H=20
W=62
Hidden=1

[D1Txt]
Meter=STRING
X=82
Y=168
H=18
W=100
MeterStyle=StyleText
Text=Wireless
Hidden=1

###

[D2]
Meter=BUTTON
ButtonImage=Button.png
X=139
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Clock\RED" "1.ini"
Hidden=1

[D2Ico]
Meter=IMAGE
ImageName=Rclock.png
X=139
Y=87
Hidden=1

[D2Blur]
Meter=IMAGE
ImageName=Blur.png
X=157
Y=167
H=20
W=69
Hidden=1

[D2Txt]
Meter=STRING
X=192
Y=168
H=18
W=100
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RED Clock
Hidden=1

###

[D3]
Meter=BUTTON
ButtonImage=Button.png
X=249
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Gallery\Window" "REDCalendar.ini"
Hidden=1

[D3Ico]
Meter=IMAGE
ImageName=Rcalendar.png
X=249
Y=87
Hidden=1

[D3Blur]
Meter=IMAGE
ImageName=Blur.png
X=256
Y=167
H=20
W=90
Hidden=1

[D3Txt]
Meter=STRING
X=302
Y=168
H=18
W=100
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RED Calendar
Hidden=1

###

[D4]
Meter=BUTTON
ButtonImage=Button.png
X=359
Y=84
ButtonCommand=!RainmeterToggleConfig "Vista Rainbar\Slideshow\RED" "RED Normal.ini"
Hidden=1

[D4Ico]
Meter=IMAGE
ImageName=Rslideshow.png
X=359
Y=87
Hidden=1

[D4Blur]
Meter=IMAGE
ImageName=Blur.png
X=362
Y=167
H=20
W=100
Hidden=1

[D4Txt]
Meter=STRING
X=412
Y=168
H=18
W=100
FontColor=#ShwColor#
FontSize=9
StringAlign=CENTER
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Clipstring=1
Text=RED Slideshow
Hidden=1