[Metadata]
Name=Sticky Notes Gadget | Yellow
Config=Vista Rainbar | Sticky Notes
Description=Take quick notes with Sticky Notes.
Instructions=The text can be alted using the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Notes
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=-1
MouseOverAction=1
MouseLeaveAction=1

[Variables]
EXT=d.txt
@Include=UserVariables.inc
Notes1=Vista Rainbar 5.0 coming soon!
Notes2=Notes 2
Notes4=Notes 4
Notes3=Notes 3
LastCat=1
###



###

[JustDoIt]
Measure=Calc
Formula=1
IfCondition=1=1
IfTrueAction=[!HideMeterGroup Notes][!ShowMeter Text#LastCat#][!ShowMeter No#LastCat#][!ShowMeter Left#LastCat#][!ShowMeter Right#LastCat#][!Update][!Redraw]
DynamicVariables=1

[StyleNo]
Y=86
FontColor=0,0,0
FontSize=9
FontFace=Segoe UI
StringAlign=CENTER
StringStyle=NORMAL
AntiAlias=1
Hidden=1
Group=Notes

[StyleText]
X=6
Y=2
H=84
W=117
FontColor=0,0,0
FontSize=#Notes_Font_Size#
FontFace=#Notes_Font#
StringAlign=LEFT
AntiAlias=1
Group=Notes
Clipstring=1
LeftMouseUpAction=!CommandMeasure Input#currentsection# "ExecuteBatch 1"
solidcolor=0,0,0,1


[InputText1]
Measure=Plugin
Plugin=InputText.dll
SolidColor=#colorskin#
X=5
Y=5
W=115
H=102
Command1=[!WriteKeyValue Variables Notes1 "$UserInput$"][!Refresh "#CURRENTCONFIG#"] 
DefaultValue="#notes1#"
StringStyle=NORMAL
AntiAlias=1
StringAlign=LEFTcenter
FontFace=#ThemeFont#
FontColor=#textcolor2#
InlineSetting=#InlineShadow#
FontSize=(#NotesFontSize#)*#scaledpi#
FocusDismiss=1

[InputText2]
Measure=Plugin
Plugin=InputText.dll
SolidColor=#colorskin#
X=5
Y=5
W=115
H=102
Command1=[!WriteKeyValue Variables Notes2 "$UserInput$"][!Refresh "#CURRENTCONFIG#"] 
DefaultValue="#notes2#"
StringStyle=NORMAL
AntiAlias=1
StringAlign=LEFTcenter
FontFace=#ThemeFont#
FontColor=#textcolor2#
InlineSetting=#InlineShadow#
FontSize=(#NotesFontSize#)*#scaledpi#
FocusDismiss=1

[InputText3]
Measure=Plugin
Plugin=InputText.dll
SolidColor=#colorskin#
X=5
Y=5
W=115
H=102
Command1=[!WriteKeyValue Variables Notes3 "$UserInput$"][!Refresh "#CURRENTCONFIG#"] 
DefaultValue="#notes3#"
StringStyle=NORMAL
AntiAlias=1
StringAlign=LEFTcenter
FontFace=#ThemeFont#
FontColor=#textcolor2#
InlineSetting=#InlineShadow#
FontSize=(#NotesFontSize#)*#scaledpi#
FocusDismiss=1

[InputText4]
Measure=Plugin
Plugin=InputText.dll
SolidColor=#colorskin#
X=5
Y=5
W=115
H=102
Command1=[!WriteKeyValue Variables Notes4 "$UserInput$"][!Refresh "#CURRENTCONFIG#"] 
DefaultValue="#notes4#"
StringStyle=NORMAL
AntiAlias=1
StringAlign=LEFTcenter
FontFace=#ThemeFont#
FontColor=#textcolor2#
InlineSetting=#InlineShadow#
FontSize=(#NotesFontSize#)*#scaledpi#
FocusDismiss=1

###

[BG]
Meter=IMAGE
ImageName=#currentpath#\Variants\#Notes_Color#.png


[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=138
h=138
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Back][!ShowMeter Close][!HideMeter Cadre][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Back][!HideMeter Close][!ShowMeter Cadre][!Redraw]




[Text1]
Text=#Notes1#
Meter=STRING
MeterStyle=StyleText

[Text2]
Text=#Notes2#
Meter=STRING
MeterStyle=StyleText
Hidden=1

[Text3]
Text=#Notes3#
Meter=STRING
MeterStyle=StyleText
Hidden=1

[Text4]
Text=#Notes4#
Meter=STRING
MeterStyle=StyleText
Hidden=1




[Cadre1]
Meter=IMAGE
ImageName=Cadre.png
X=27
Y=85
Hidden=0



[Left1]
Meter=BUTTON
ButtonImage=Left.png
X=29
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 4][!HideMeter 1][!HideMeter Text1][!HideMeter Left1][!HideMeter Right1][!HideMeter No1][!HideMeter Plus1][!ShowMeter 4][!ShowMeter Text4][!ShowMeter Left4][!ShowMeter Right4][!ShowMeter No4][!ShowMeter Plus4][!Redraw]
Hidden=1

[Left2]
Meter=BUTTON
ButtonImage=Left.png
X=29
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 1][!HideMeter 2][!HideMeter Text2][!HideMeter Left2][!HideMeter Right2][!HideMeter No2][!HideMeter Plus2][!ShowMeter 1][!ShowMeter Text1][!ShowMeter Left1][!ShowMeter Right1][!ShowMeter No1][!ShowMeter Plus1][!Redraw]
Hidden=1

[Left3]
Meter=BUTTON
ButtonImage=Left.png
X=29
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 2][!HideMeter 3][!HideMeter Text3][!HideMeter Left3][!HideMeter Right3][!HideMeter No3][!HideMeter Plus3][!ShowMeter 2][!ShowMeter Text2][!ShowMeter Left2][!ShowMeter Right2][!ShowMeter No2][!ShowMeter Plus2][!Redraw]
Hidden=1

[Left4]
Meter=BUTTON
ButtonImage=Left.png
X=29
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 3][!HideMeter 4][!HideMeter Text4][!HideMeter Left4][!HideMeter Right4][!HideMeter No4][!HideMeter Plus4][!ShowMeter 3][!ShowMeter Text3][!ShowMeter Left3][!ShowMeter Right3][!ShowMeter No3][!ShowMeter Plus3][!Redraw]
Hidden=1

[Right1]
Meter=BUTTON
ButtonImage=Right.png
X=85
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 2][!HideMeter 1][!HideMeter Text1][!HideMeter Left1][!HideMeter Right1][!HideMeter No1][!HideMeter Plus1][!ShowMeter 2][!ShowMeter Text2][!ShowMeter Left2][!ShowMeter Right2][!ShowMeter No2][!ShowMeter Plus2][!Redraw]
Hidden=1

[Right2]
Meter=BUTTON
ButtonImage=Right.png
X=85
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 3][!HideMeter 2][!HideMeter Text2][!HideMeter Left2][!HideMeter Right2][!HideMeter No2][!HideMeter Plus2][!ShowMeter 3][!ShowMeter Text3][!ShowMeter Left3][!ShowMeter Right3][!ShowMeter No3][!ShowMeter Plus3][!Redraw]
Hidden=1

[Right3]
Meter=BUTTON
ButtonImage=Right.png
X=85
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 4][!HideMeter 3][!HideMeter Text3][!HideMeter Left3][!HideMeter Right3][!HideMeter No3][!HideMeter Plus3][!ShowMeter 4][!ShowMeter Text4][!ShowMeter Left4][!ShowMeter Right4][!ShowMeter No4][!ShowMeter Plus4][!Redraw]
Hidden=1

[Right4]
Meter=BUTTON
ButtonImage=Right.png
X=85
Y=87
ButtonCommand=!Execute [!WriteKeyValue Variables LastCat 1][!HideMeter 4][!HideMeter Text4][!HideMeter Left4][!HideMeter Right4][!HideMeter No4][!HideMeter Plus4][!ShowMeter 1][!ShowMeter Text1][!ShowMeter Left1][!ShowMeter Right1][!ShowMeter No1][!ShowMeter Plus1][!Redraw]
Hidden=1

[No1]
Meter=STRING
MeterStyle=StyleNo
X=65
Text=1/4

[No2]
Meter=STRING
X=65
MeterStyle=StyleNo
Text=2/4

[No3]
Meter=STRING
X=65
MeterStyle=StyleNo
Text=3/4

[No4]
Meter=STRING
X=65
MeterStyle=StyleNo
Text=4/4

###

[Cadre]
Meter=IMAGE
ImageName=#Notes_Color#.png
X=27
Y=85
w=76
h=20
Hidden=0

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1



[More]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1
