[Metadata]
Name=Multi-Meter Gadget | Process
Config=Vista Rainbar | Multi-Meter
Description=Displays current CPU, RAM, and SWAP usage.
Version=5.0
Tags=Gadget | Vista Rainbar | System | CPU | RAM
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com


[img]
Meter=IMAGE

imagename=Fond.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=137
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]
Update=2000

[Variables]
FontName=Segoe UI
TxtColor=255,255,255,200
ShwColor=0,0,0,200

###

[MeasureRAM]
Measure=PhysicalMemory
Substitute="G":"GB","M":"MB"

[MeasureRAMTotal]
Measure=PhysicalMemory
Total=1
Substitute="G":"GB","M":"MB"

[MeasureSWAP]
Measure=SwapMemory
Substitute="G":"GB","M":"MB"

[MeasureSWAPTotal]
Measure=SwapMemory
Total=1
Substitute="G":"GB","M":"MB"

[MeasureCPU]
Measure=CPU

[MeasureTopProcess]
Measure=Plugin
Plugin=Plugins\AdvancedCPU.dll
TopProcess=2
CPUExclude=Idle

[MeasureTopProcess2]
Measure=Plugin
Plugin=Plugins\AdvancedCPU.dll
TopProcess=1
CPUExclude=Idle

###

[RAMGraph]
Meter=LINE
MeasureName=MeasureRAM
X=2
Y=6
H=13
W=119
LineCount=1
LineColor=5,67,5
AntiAlias=1

[RAMTxtShw]
Meter=STRING
X=4
Y=5
FontColor=#ShwColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName#
Text=RAM
Percentual=1
AntiAlias=1

[RAMTxt]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName#
Text=RAM
Percentual=1
AntiAlias=1

[RAMShw]
MeasureName=MeasureRAM
Meter=STRING
X=116
Y=5
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=8
StringAlign=RIGHT
FontFace=#FontName#
Text=%1%
Percentual=1
AntiAlias=1

[RAM]
MeasureName=MeasureRAM
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=8
StringAlign=RIGHT
FontFace=#FontName#
Text=%1%
Percentual=1
AntiAlias=1

[RAMTotShw]
Meter=STRING
MeasureName=MeasureRAM
MeasureName2=MeasureRAMTotal
X=10
Y=19
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=7
StringAlign=LEFT
FontFace=#FontName#
AntiAlias=1
AutoScale=1
NumOfDecimals=0
Text=%1/%2

[RAMTot]
Meter=STRING
MeasureName=MeasureRAM
MeasureName2=MeasureRAMTotal
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=7
StringAlign=LEFT
FontFace=#FontName#
AntiAlias=1
AutoScale=1
NumOfDecimals=0
Text=%1/%2

[SWAPGraph]
Meter=LINE
MeasureName=MeasureSWAP
X=2
Y=34
H=13
W=119
LineCount=1
LineColor=5,67,5
AntiAlias=1

[SWAPTxtShw]
Meter=STRING
X=4
Y=33
FontColor=#ShwColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName#
Text=SWAP
Percentual=1
AntiAlias=1

[SWAPTxt]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName#
Text=SWAP
Percentual=1
AntiAlias=1

[SWAPShw]
MeasureName=MeasureSWAP
Meter=STRING
X=116
Y=33
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=8
StringAlign=RIGHT
FontFace=#FontName#
Text=%1%
Percentual=1
AntiAlias=1

[SWAP]
MeasureName=MeasureSWAP
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=8
StringAlign=RIGHT
FontFace=#FontName#
Text=%1%
Percentual=1
AntiAlias=1

[SWAPTotShw]
Meter=STRING
MeasureName=MeasureSWAP
MeasureName2=MeasureSWAPTotal
X=10
Y=47
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=7
StringAlign=LEFT
FontFace=#FontName#
AntiAlias=1
AutoScale=1
NumOfDecimals=0
Text=%1/%2

[SWAPTot]
Meter=STRING
MeasureName=MeasureSWAP
MeasureName2=MeasureSWAPTotal
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=7
StringAlign=LEFT
FontFace=#FontName#
AntiAlias=1
AutoScale=1
NumOfDecimals=0
Text=%1/%2

[CPUGraph]
Meter=LINE
MeasureName=MeasureCPU
X=2
Y=62
H=13
W=119
LineCount=1
LineColor=5,67,5
AntiAlias=1

[CPUTxtShw]
Meter=STRING
X=4
Y=61
FontColor=#ShwColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName#
Text=CPU
NumOfDecimals=1
AntiAlias=1

[CPUTxt]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName#
Text=CPU
NumOfDecimals=1
AntiAlias=1

[CPUShw]
MeasureName=MeasureCPU
Meter=STRING
X=116
Y=61
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=8
StringAlign=RIGHT
FontFace=#FontName#
Text=%1%
NumOfDecimals=1
AntiAlias=1

[CPU]
MeasureName=MeasureCPU
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=8
StringAlign=RIGHT
FontFace=#FontName#
Text=%1%
NumOfDecimals=1
AntiAlias=1

[ProcessShw]
MeasureName=MeasureTopProcess
MeasureName2=MeasureTopProcess2
Meter=STRING
X=4
Y=75
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=7
StringAlign=LEFT
FontFace=#FontName#
AntiAlias=1
NumOfDecimals=1
Scale=100000
Text=- %1 %2%

[Process]
MeasureName=MeasureTopProcess
MeasureName2=MeasureTopProcess2
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=7
StringAlign=LEFT
FontFace=#FontName#
AntiAlias=1
NumOfDecimals=1
Scale=100000
Text=- %1 %2%

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=118
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Multi-Meter" "Black.ini"
Hidden=1
