[Metadata]
Name=Network Gadget | Style 1
Config=Vista Rainbar | Network
Description=Displays the network bandwidth consumption and IP address.
Version=5.0
Tags=Gadget | Vista Rainbar | Network
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com



[img]
Meter=IMAGE
imagename=Reseau2.png


[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=138
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
SpeedUnitName=kB/s
SpeedUnit=1000
FontName2=Segoe UI
TxtColor=255,255,255
ShwColor=0,0,0

###

[MeasureNetIn]
Measure=NetIn

[MeasureIn]
Measure=Calc
Formula=(MeasureNetIn/#SpeedUnit#)

[MeasureNetOut]
Measure=NetOut

[MeasureOut]
Measure=Calc
Formula=(MeasureNetOut/#SpeedUnit#)

[MeasureIPWeb]
Measure=Plugin
Plugin=Plugins\WebParser.dll
URL=http://checkip.dyndns.org
RegExp="(?siU)<body>.*Address: (.*)</body>"
StringIndex=1
UpdateRate=14400

###

[NetIn]
Meter=STRING
MeasureName=MeasureIn
X=120
Y=11
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=9
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[NetIn2]
Meter=STRING
MeasureName=MeasureIn
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=9
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[InText]
Meter=STRING
X=55
Y=11
FontColor=#ShwColor#
StringStyle=BOLD
FontSize=9
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="D:"

[InText2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="D:"

[NetOut]
Meter=STRING
MeasureName=MeasureOut
X=120
Y=25
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=9
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[NetOut2]
Meter=STRING
MeasureName=MeasureOut
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=9
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[OutText]
Meter=STRING
X=55
Y=25
FontColor=#ShwColor#
StringStyle=BOLD
FontSize=9
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="U:"

[OutText2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=9
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="U:"

[IPweb]
Meter=STRING
MeasureName=MeasureIPweb
X=120
Y=42
FontColor=#ShwColor#
StringStyle=NORMAL
FontSize=7
StringAlign=right
FontFace=#FontName2#
AntiAlias=1

[IPweb2]
Meter=STRING
MeasureName=MeasureIPweb
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=7
StringAlign=right
FontFace=#FontName2#
AntiAlias=1

[Icon2]
Meter=IMAGE
ImageName=Network2.png
X=-2
Y=-1
H=37
W=37
Hidden=1

[Icon]
Meter=IMAGE
ImageName=Network3.png
X=0
Y=-7
H=54
W=54
MouseOverAction=!Execute [!ShowMeter Icon2][!Redraw]
MouseLeaveAction=!Execute [!HideMeter Icon2][!Redraw]
LeftMouseUpAction=!execute [::{7007ACC7-3202-11D1-AAD2-00805FC1270E}]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuX.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

