[Metadata]
Name=Network Gadget | Style 3
Config=Vista Rainbar | Network
Description=Displays the network bandwidth consumption and IP address.
Version=5.0
Tags=Gadget | Vista Rainbar | Network
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Reseau1.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=165
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
SpeedUnitName=kB/s
SpeedUnit=1000
FontName2=Microsoft Sans Serif
TxtColor=255,255,255,225
ShwColor=0,0,0,200

###

[MeasureNetIn]
Measure=NetIn

[MeasureIn]
Measure=Calc
Formula=(MeasureNetIn/#SpeedUnit#)

[MeasureNetOut]
Measure=NetOut

[MeasureOut]
Measure=Calc
Formula=(MeasureNetOut/#SpeedUnit#)

[MeasureIPWeb]
Measure=Plugin
Plugin=Plugins\WebParser.dll
URL=http://checkip.dyndns.org
RegExp="(?siU)<body>.*Address: (.*)</body>"
StringIndex=1
UpdateRate=14400

###

[NetOut]
Meter=STRING
MeasureName=MeasureOut
X=142
Y=21
FontColor=#ShwColor#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[NetOut2]
Meter=STRING
MeasureName=MeasureOut
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[OutText]
Meter=STRING
X=57
Y=21
FontColor=#ShwColor#
StringStyle=Bold
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="U:"

[OutText2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=Bold
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="U:"

[NetIn]
Meter=STRING
MeasureName=MeasureIn
X=142
Y=9
FontColor=#ShwColor#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[NetIn2]
Meter=STRING
MeasureName=MeasureIn
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
Postfix=#SpeedUnitName#

[InText]
Meter=STRING
X=57
Y=9
FontColor=#ShwColor#
StringStyle=Bold
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="D:"

[InText2]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=Bold
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
Text="D:"

[IPweb]
Meter=STRING
MeasureName=MeasureIPweb
X=142
Y=33
FontColor=#ShwColor#
StringStyle=BOLD
FontSize=7
StringAlign=right
FontFace=#FontName2#
Prefix="IP "
AntiAlias=1

[IPweb2]
Meter=STRING
MeasureName=MeasureIPweb
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=7
StringAlign=right
FontFace=#FontName2#
AntiAlias=1

[Icon]
Meter=IMAGE
#ImageName=Network2.png
X=0
Y=0
W=48
H=42
LeftMouseUpAction=!execute [::{7007ACC7-3202-11D1-AAD2-00805FC1270E}]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=148
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=148
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=148
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Network" "1.ini"
Hidden=1
