[Metadata]
Name=Analog Clock Gadget | Simple
Config=Vista Rainbar | Clock | Normal
Description=Display the time in analog form.
Version=5.0
Tags=Gadget | Vista Rainbar | Clock | Time
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=#Show_Seconds#000


[Variables]
@Include2=UserVariables.inc


[img]
Meter=IMAGE
w=130
h=135
ImageName=bezel.png
x=10

[zone]
Meter=IMAGE
w=125
h=125
x=10
y=4
ImageName=#currentpath#Variants\#Continent#.png


[MeterNight]
Meter=IMAGE
w=125
h=125
x=10
y=4
ImageName=#currentpath#Variants\#Continent#Dark.png
Hidden=1
Group=Night

[MeasureNight]
Measure=Calc
Formula=([H]>=22) || ([H]<7)
DynamicVariables=1
IfCondition=MeasureNight=1
IfTrueAction=[!ShowMeterGroup Night][!Redraw]
IfFalseAction=[!HideMeterGroup Night][!Redraw]
Disabled=#Night_Mode#

[fade]
Meter=IMAGE
w=125
h=124
x=11
y=2
ImageName=#currentpath#day2night_transparency_small\[H].png

[3]
Meter=IMAGE
w=122
h=122
x=12
y=4
ImageName=clock_tickmarks_small.png

[TicksNight]
Meter=IMAGE
w=125
h=125
x=10
y=4
ImageName=clock_tickmarks_smallDark.png
Hidden=1
Group=Night



[More1]
Meter=shape
Shape=Ellipse 73,65,55 | Fill Color 120,120,120,150
Group=More
Hidden=1

[Txt]
Meter=STRING
MeasureName=1
X=74
Y=80
H=16
W=74
FontColor=0,0,0
FontSize=10
StringAlign=CENTER
StringStyle=BOLD
Antialias=1
Clipstring=1
Group=More
Hidden=1


[2]
Meter=IMAGE
w=125
h=125
x=11
y=3
ImageName=rim.png




[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=140

MouseOverAction=!execute [!ShowMeter Menu][!ShowMeterGroup More][!ShowMeter Close][!ShowMeter Plus][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeterGroup More][!HideMeter Close][!HideMeter Plus][!Redraw]

[Variables]
Value=
@Include=settings.inc

[MeasureTime]
Measure=Time

[MeasureTime2]
Measure=Time
Format=%d

[H]
Measure=Time
Format=%H


[1]
Measure=Time
Format=%H:%M

[2]
Measure=Time
Format=%I:%M %p


[4]
Measure=Time
Format=%Z

###





[Hours]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=heureSimple.png
X=73
Y=63
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=43200
OffsetX=6
OffsetY=64


[Minutes]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=minuteSimple.png
X=73
Y=63
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=3600
OffsetX=6
OffsetY=64

[Point]
Meter=IMAGE
ImageName=pointSimple#Show_Seconds#.png
X=68
Y=-1



[Secondes]
MeasureName=MeasureTime
Meter=ROTATOR
ImageName=secondeSimple#Show_Seconds#.png
X=73
Y=63
StartAngle=6.2832
RotationAngle=6.2832
ValueReminder=60
OffsetX=6
OffsetY=64


###




[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=120
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=120
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Plus]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=120
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1

