[Metadata]
Name=Slideshow Gadget | Normal+
Config=Vista Rainbar | Slideshow
Description=Displays a slideshow of pictures from selected folder.
Instructions=Use configuration tool to set picture folder.
Version=5.0
Tags=Gadget | Vista Rainbar | Slideshow
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com


Update=(#Slideshow_Speed#*60000)

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=380
h=250
MouseOverAction=!execute [!ShowMeter Popup][!ShowMeter Pause][!ShowMeter Next][!ShowMeter Explorer][!ShowMeter Previous][!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!ShowMeter Plus][!ShowMeter Set][!Redraw]
MouseLeaveAction=!execute [!HideMeter Popup][!HideMeter Pause][!HideMeter Next][!HideMeter Previous][!HideMeter Explorer][!HideMeter Menu][!HideMeter More][!HideMeter Close][!HideMeter Plus][!HideMeter Set][!Redraw]



[Variables]
@Include=UserVariables.inc

###

[Random]
Measure=Plugin
Plugin=Plugins\QuotePlugin.dll
PathName="#Pictures_Folder#"
Subfolders=1
FileFilter=*.jpg;*.jpeg;*.gif;*.png

###

[Background]
Meter=IMAGE
ImageName=bigframe.png
X=0
Y=0

[Image]
MeasureName=Random
Meter=IMAGE
X=17
Y=16
W=320
H=240

[PopUp]
Meter=IMAGE
ImageName=bg_sidebar.png
X=119
Y=230
Hidden=1

[Previous]
Meter=BUTTON
ButtonImage=prev.png
X=126
Y=233
ButtonCommand=!Execute [!RainmeterRefresh]
Hidden=1

[Pause]
Meter=BUTTON
ButtonImage=pause.png
X=152
Y=233
Hidden=1

[Next]
Meter=BUTTON
ButtonImage=Next.png
X=175
Y=233
ButtonCommand=!Execute [!RainmeterRefresh]
Hidden=1

[Explorer]
Meter=BUTTON
ButtonImage=explorer.png
X=199
Y=233
ButtonCommand=!Execute ["[Random]"]
Hidden=1


###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXMS.png
X=360
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=360
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Plus]
Meter=BUTTON
ButtonImage=#@#img\Minus.png
X=360
Y=21
ButtonCommand=!Execute [!ActivateConfig "Vista Rainbar\Slideshow" "Normal.ini"][!RainmeterRefresh]
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=360
Y=42
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1