[Metadata]
Name=Power Gadget | Style 2
Config=Vista Rainbar | Power
Description=A gadget to shutdown, reboot, or sleep your computer.
Version=5.0
Tags=Gadget | Vista Rainbar | System | Power
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=600000
UpdateDivider=180


[img]
meter=IMAGE

imagename=Background.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=140
h=75
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
FontName=Segoe UI
TxtColor=220,220,220
ShwColor=0,0,0

@include=#@#Global.inc
@include1=Extra.inc
@include2=UserVariables.inc

[MeasureDay]
Measure=TIME
Format=%d
;TimeZone=#_TimeZone#
DaylightSavingTime=#_DayLightSavingsTime#

[MeasureMonth]
Measure=TIME
Format=%m
;TimeZone=#_TimeZone#
DaylightSavingTime=#_DayLightSavingsTime#

[MeasureYear]
Measure=TIME
Format=%Y
;TimeZone=#_TimeZone#

[MeasureLuaScript]
Measure=SCRIPT
ScriptFile=#CURRENTPATH#Sun.lua


[UptimeShw]

Meter=STRING
X=64
Y=37
FontColor=#ShwColor#
FontSize=9
FontFace=#FontName#
StringStyle=BOLD
StringAlign=CENTER
AntiAlias=1
Text=Sunset: #_Set#
DynamicVariables=1


[Uptime]
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=9
FontFace=#FontName#
StringStyle=BOLD
StringAlign=CENTER
AntiAlias=1
Text=Sunset: #_Set#
DynamicVariables=1

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXS.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=21
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1

