[Variables]
URL1=http://newsrss.bbc.co.uk/rss/newsonline_world_edition/front_page/rss.xml
URL2=http://feeds.nytimes.com/nyt/rss/HomePage
URL3=http://feeds.gawker.com/gizmodo/excerpts.xml
SubstituteLink="&amp;":"&","<![CDATA[":"","]]>":""
Substitute="&apos;":"'","&quot;":"”","&Quot;":"”","&amp;":"&","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":"","&#39;":"'","&#228;":"ä","&#246;":"ö","&#8211;":"–","&gt;":">","&ndash;":"–","&mdash;":"—"