[Metadata]
Name=Media Player Gadget | iTunes
Config=Vista Rainbar | Media Player
Description=A gadget to control music playback of iTunes.
Version=5.0
Tags=Gadget | Vista Rainbar | Music | iTunes
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png
Variant=1

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Glass.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Close][!Redraw]

[Variables]
exec=iTunes.exe

###

[MeasurePrev]
Measure=Plugin
Plugin=Plugins\iTunesPlugin.dll
Command=PreviousTrack

[MeasurePlay]
Measure=Plugin
Plugin=Plugins\iTunesPlugin.dll
Command=PlayPause

[MeasureNext]
Measure=Plugin
Plugin=Plugins\iTunesPlugin.dll
Command=NextTrack

[MeasureStop]
Measure=Plugin
Plugin=Plugins\iTunesPlugin.dll
Command=Stop

###

[Prev]
Meter=BUTTON
ButtonImage=Previous1.png
X=4
Y=13
ButtonCommand=!RainmeterPluginBang "MeasurePrev"

[Play]
Meter=BUTTON
ButtonImage=Play1.png
X=43
Y=7
ButtonCommand=!RainmeterPluginBang "MeasurePlay"

[Next]
Meter=BUTTON
ButtonImage=Next1.png
X=79
Y=13
ButtonCommand=!RainmeterPluginBang "MeasureNext"

[Stop]
Meter=BUTTON
ButtonImage=Stop1.png
X=11
Y=49
ButtonCommand=!RainmeterPluginBang "MeasureStop"

[Button]
Meter=BUTTON
ButtonImage=Launch1.png
X=93
Y=49
ButtonCommand=!Execute ["#exec#"]

[Volume]
Meter=BUTTON
ButtonImage=Volume1.png
X=52
Y=49
ButtonCommand=!Execute [sndvol32.exe /t]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuX.png
X=130
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=130
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1
