[Metadata]
Name=Media Player Gadget | WMP | Style 1
Config=Vista Rainbar | Media Player
Description=A gadget to control music playback of Window Media Player.
Version=5.0
Tags=Gadget | Vista Rainbar | Music
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com



[img]
Meter=IMAGE
imagename=Glass.png



[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=138
h=100
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
exec=wmplayer.exe

[Commands]
Measure=Plugin
Plugin=Plugins\WindowMessagePlugin.dll
WindowClass=WMPlayerApp

###

[Prev]
Meter=BUTTON
ButtonImage=Previous1.png
X=4
Y=13
ButtonCommand=!RainmeterPluginBang "Commands SendMessage 273 18810 0" 

[Play]
Meter=BUTTON
ButtonImage=Play1.png
X=43
Y=7
ButtonCommand=!RainmeterPluginBang "Commands SendMessage 273 18808 0"

[Next]
Meter=BUTTON
ButtonImage=Next1.png
X=79
Y=13
ButtonCommand=!RainmeterPluginBang "Commands SendMessage 273 18811 0"

[Stop]
Meter=BUTTON
ButtonImage=Stop1.png
X=11
Y=49
ButtonCommand=!RainmeterPluginBang "Commands SendMessage 273 18809 0"

[Button]
Meter=BUTTON
ButtonImage=Launch1.png
X=93
Y=49
ButtonCommand=!Execute ["#exec#"]

[Volume]
Meter=BUTTON
ButtonImage=Volume1.png
X=52
Y=49
ButtonCommand=!Execute [sndvol32.exe /t]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=118
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Media Player" "WMP2.ini"
Hidden=1
