[Metadata]
Name=Date Gadget | Style 1
Config=Vista Rainbar | Date
Description=Displays the current day, month, and year.
Version=5.0
Tags=Gadget | Vista Rainbar | Date
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com


[img]
Meter=IMAGE
imagename=Fond.png

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=138
h=70
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
FontName=Segoe UI
TxtColor=255,255,255,235
ShwColor=0,0,0,200

###

[MeasureYear]
Measure=Time
Format=%Y

[MeasureMonth]
Measure=Time
Format=%B

[MeasureDay]
Measure=Time
Format=%A

[MeasureDate]
Measure=Time
Format=%d

###

[Style1]
FontFace=#FontName#
StringStyle=NORMAL
AntiAlias=1
StringAlign=CENTER

[Style2]
FontFace=#FontName#
StringStyle=BOLD
AntiAlias=1
StringAlign=CENTER
FontSize=10

###

[Background]
Meter=IMAGE
ImageName=Fond.png
X=0
Y=0

[Year]
Meter=STRING
MeasureName=MeasureYear
X=65
Y=-7
FontColor=255,255,255,55
FontSize=40
MeterStyle=Style1

[DayShw]
MeasureName=MeasureDay
Meter=STRING
X=41
Y=10
FontColor=#ShwColor#
FontSize=10
MeterStyle=Style1

[Day]
MeasureName=MeasureDay
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=10
MeterStyle=Style1

[DateShw]
MeasureName=MeasureDate
Meter=STRING
X=98
Y=4
FontColor=#ShwColor#
FontSize=30
MeterStyle=Style1

[Date]
MeasureName=MeasureDate
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=30
MeterStyle=Style1

[MonthShw]
MeasureName=MeasureMonth
Meter=STRING
X=41
Y=37
FontColor=#ShwColor#
MeterStyle=Style2

[Month]
MeasureName=MeasureMonth
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
MeterStyle=Style2

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuX.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1
