[Metadata]
Name=Date Gadget | Style 2
Config=Vista Rainbar | Date
Description=Displays the current day, month, and year.
Version=5.0
Tags=Gadget | Vista Rainbar | Date
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=Fond2.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
FontName=Segoe UI
TxtColor=255,255,255,235
ShwColor=0,0,0,200

###

[MeasureYear]
Measure=Time
Format=%Y

[MeasureMonth]
Measure=Time
Format=%B

[MeasureDay]
Measure=Time
Format=%A

[MeasureDate]
Measure=Time
Format=%d

###

[Style1]
FontFace=#FontName#
StringStyle=NORMAL
AntiAlias=1
StringAlign=CENTER

###

[Year]
Meter=STRING
MeasureName=MeasureYear
X=66
Y=-12
FontColor=255,255,255,55
FontSize=40
MeterStyle=Style1

[DayShw]
MeasureName=MeasureDay
Meter=STRING
X=51
Y=27
FontColor=#ShwColor#
FontSize=10
MeterStyle=Style1
StringAlign=LEFT

[Day]
MeasureName=MeasureDay
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=10
MeterStyle=Style1
StringAlign=LEFT

[DateShw]
MeasureName=MeasureDate
Meter=STRING
X=27
Y=1
FontColor=#ShwColor#
FontSize=28
MeterStyle=Style1

[Date]
MeasureName=MeasureDate
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=28
MeterStyle=Style1

[MonthShw]
MeasureName=MeasureMonth
Meter=STRING
X=51
Y=9
FontColor=#ShwColor#
FontSize=10
MeterStyle=Style1
StringStyle=BOLD
StringAlign=LEFT

[Month]
MeasureName=MeasureMonth
Meter=STRING
X=1r
Y=-1r
FontColor=#TxtColor#
FontSize=10
MeterStyle=Style1
StringStyle=BOLD
StringAlign=LEFT

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=130
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=130
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=130
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Date" "1.ini"
Hidden=1
