[Metadata]
Name=Disk Gadget (6) | Style 5
Config=Vista Rainbar | Disk | 6
Description=Displays the usage of disk.
Version=5.0
Tags=Gadget | Vista Rainbar | Disk
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
Update=10000
MouseActionCursor=0
Author=legace@inbox.com

Background=..\img\Disque4.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
Disk6=H:
NumOfDec=0
@Include=..\settings.inc
FontName=Segoe UI
TxtColor=255,255,255
Shw_Color=0,0,0

[MeasureDiskFree]
Measure=FreeDiskSpace
Drive=#Disk6#
Substitute="G":"GB","M":"MB","K":"KB"

[MeasureDiskUsed]
Measure=FreeDiskSpace
Drive=#Disk6#
Substitute="G":"GB","M":"MB","K":"KB"
InvertMeasure=1

[MeasureDiskTotal]
Measure=FreeDiskSpace
Drive=#Disk6#
Substitute="G":"GB","M":"MB","K":"KB"
Total=1

###

[DiskFreeBar]
MeasureName=MeasureDiskUsed
Meter=BAR
X=22
Y=34
H=7
W=121
BarImage=..\img\Bleu.png
BarOrientation=HORIZONTAL

[DiskNumShw]
Meter=STRING
MeasureName=MeasureDiskUsed
MeasureName2=MeasureDiskTotal
X=140
Y=19
FontColor=#Shw_Color#
StringStyle=NORMAL
FontSize=8
StringAlign=right
FontFace=#FontName#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Text=%1 / %2

[DiskNum]
Meter=STRING
MeasureName=MeasureDiskUsed
MeasureName2=MeasureDiskTotal
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=8
StringAlign=right
FontFace=#FontName#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Text=%1 / %2

[DiskPercentShw]
Meter=STRING
MeasureName=MeasureDiskUsed
X=140
Y=4
FontColor=#Shw_Color#
StringStyle=NORMAL
FontSize=9
StringAlign=RIGHT
FontFace=#FontName#
AntiAlias=1
AutoScale=1
Percentual=1
Prefix="(#Disk6#)         "
Postfix=%

[DiskPercent]
Meter=STRING
MeasureName=MeasureDiskUsed
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=9
StringAlign=RIGHT
FontFace=#FontName#
AntiAlias=1
AutoScale=1
Percentual=1
Prefix="(#Disk6#)         "
Postfix=%

[Icon]
Meter=IMAGE
X=6
Y=8
W=48
H=22
RightMouseDownAction=!execute ["explorer.exe /root,,#Disk6#"]

[HDDIcon]
Meter=BUTTON
ButtonImage=#@#img\HDD1Button.png
X=0
Y=-30
ButtonCommand=!Execute [#Disk6#]


###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=149
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=149
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=149
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Disk\6" "6.ini"
Hidden=1
