[Metadata]
Name=Buy RED Gadget | Style 1
Config=Vista Rainbar | Clock | RED
Description=Display the time in analog form.
Version=5.0
Tags=Gadget | Vista Rainbar | Clock | Time
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=-1

RightMouseUpAction=[!SkinCustomMenu]
ContextTitle=Alternative
ContextAction=!ActivateConfig "#currentconfig#" "2.ini"
ContextTitle2=----
ContextAction2=[]
ContextTitle3=Settings
ContextAction3=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
ContextTitle4=Close
ContextAction4=!DeactivateConfig
ContextTitle5=----
ContextAction5=[]
ContextTitle6=More Actions
ContextAction6=[!SkinMenu]


[Variables]
@include=UserVariables.inc

[img]
Meter=IMAGE

ImageName=idleBackground.png
LeftMouseUpAction=!execute [""]
MouseActionCursor=1 
w=145
h=50

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=148
h=50
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Close][!Redraw]




[bg3]
Meter=Image
SolidColor=255,255,255,255
W=90
H=15
X=15
Y=15
LeftMouseUpAction=!CommandMeasure Input "ExecuteBatch 1"

[search]
Meter=Image
X=110
Y=13
LeftMouseUpAction=["https://#search_engine#[Input]"]
imagename=idleButton.png
DynamicVariables=1
ToolTipText=Press ENTER to search
[Input]
Measure=Plugin
Plugin=InputText.dll
W=90
H=15
X=15
Y=15
DynamicVariables=1
SolidColor=255,255,255,255
FontColor=0,0,0
FontSize=9
FontFace=Segoe UI
AntiAlias=1
FocusDismiss=1
Command1=["https://#search_engine#$UserInput$"]
DefaultValue=""

###

[Close]
Meter=BUTTON
ButtonImage=#@#\Graphics\Sidebar\Dropdown.png
X=134
Y=0
ButtonCommand=!SkinCustomMenu
Hidden=1