[Metadata]
Name=RSS Gadget #1 | Feeds | Style 1
Config=Vista Rainbar | Feeds | RSS | Feeds | 1
Description=Displays the latest items from any RSS or Atom feed.
Instructions=Use the configuration tool to change your feed URL.
Version=5.0
Tags=Gadget | Feeds | Vista Rainbar | Feeds | RSS | Feeds | Feed
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
Author=legace@inbox.com

Update=60000
ContextTitle=Settings
ContextAction=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
ContextTitle2=Close
ContextAction2=!DeactivateConfig
ContextTitle3=----
ContextAction3=[]
ContextTitle4=More Actions
ContextAction4=[!SkinMenu]

[img]
Meter=IMAGE
w=152
h=168
ImageName=sticky_yellow.png
MouseActionCursor=0
ScaleMargins=10, 50, 10, 50

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=158
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!ShowMeter Set][!ShowMeter Plus][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!HideMeter Set][!HideMeter Plus][!Redraw]

[Variables]

Substitute="":"","^\s+":"","<!\[CDATA\[":"","\]\]>":"","!\[CDATA\[":"","\]\]":""
get=<item>.*<title>(.*)</title>.*<link>(.*)</link>.*</item>.*
@Include=UserVariables.inc
FontName=Segoe UI
FontName2=Calibri
TxtColor=255,255,255
TxtColor2=255,255,255,120
ShwColor=0,0,0,100
HideHint=1


Item=(?(?=.*<item>).*<item>.*<title>(.*)</title>.*<link>(.*)</link>.*<pubDate>(.*)</pubDate>)
Sub="^\s+":"","<!\[CDATA\[":"","\]\]>":"","!\[CDATA\[":"","\]\]":""

LastCat=1


[JustDoIt]
Measure=Calc
Formula=1
IfCondition=1=1
IfTrueAction=[!HideMeterGroup Feeds][!ShowMeterGroup #LastCat#][!Update][!Redraw]
DynamicVariables=1


[MeasureSite]
Measure=WebParser
URL=https://#Rss_Link#
RegExp=(?siU)<title>(.*)</title>.*<link>(.*)</link>.*#Item##Item##Item##Item##Item##Item##Item##Item##Item##Item##Item##Item#
FinishAction=!Update "#CURRENTCONFIG#"

[MeasureSiteTitle]
Measure=WebParser
URL=[MeasureSite]
StringIndex=1
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[1Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=3
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[1Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=4

[1Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=5
Substitute=",":""

;Item 2 info

[2Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=6
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[2Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=7

[2Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=8
Substitute=",":""
;Item 3 info

[3Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=9
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[3Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=10

[3Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=11
Substitute=",":""
;Item 4 info

[4Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=12
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[4Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=13

[4Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=14
Substitute=",":""
;Item 5 info

[5Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=15
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[5Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=16

[5Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=17
Substitute=",":""
;Item 5 info

[6Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=18
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[6Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=19

[6Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=20
Substitute=",":""
;Item 5 info

[7Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=21
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[7Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=22

[7Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=23
Substitute=",":""
;Item 5 info

[8Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=24
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[8Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=25

[8Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=26
Substitute=",":""

;Item 5 info

[9Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=27
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[9Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=28
[9Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=29
Substitute=",":""
;Item 5 info

[10Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=30
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[10Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=31

[10Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=32
Substitute=",":""
;Item 5 info

[11Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=33
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[11Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=34

[11Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=35
Substitute=",":""

;Item 5 info

[12Title]
Measure=WebParser
URL=[MeasureSite]
StringIndex=36
DecodeCharacterReference=1
RegExpSubstitute=1
Substitute=#Sub#

[12Link]
Measure=WebParser
URL=[MeasureSite]
StringIndex=37

[12Date]
Measure=WebParser
URL=[MeasureSite]
StringIndex=38
Substitute=",":""


[RSSStyle]
W=120
H=28
Y=R
X=15
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=8
StringAlign=LEFT
FontFace=#FontName2#
AntiAlias=1
ClipString=1
ToolTipText=%1

[Feeds]
Group=Feeds
Hidden=1


[1]
Group=1
Hidden=0

[2]
Group=2
Hidden=1

[3]
Group=3
Hidden=1
###





[RSS1]
MeasureName=1Title
Meter=STRING
Y=39
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[1Link]]

[RSS2]
MeasureName=2Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[2Link]]

[RSS3]
MeasureName=3Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[3Link]]

[RSS4]
MeasureName=4Title
Meter=STRING
MeterStyle=RSSStyle | Feeds | 1
LeftMouseUpAction=!Execute [[4Link]]



[Num]
Meter=STRING
X=15
Y=22
w=100
ClipString=1
FontColor=#TxtColor#
StringStyle=NORMAL
FontSize=9
StringAlign=Left
FontFace=#FontName2#
AntiAlias=1
MeasureName=MeasureSiteTitle


###




[Close]
Meter=BUTTON
ButtonImage=#@#\Graphics\Sidebar\Dropdown.png
X=136
Y=5
ButtonCommand=!SkinCustomMenu
Hidden=1
