[Metadata]
Name=Recycle Bin Gadget | Style 2
Config=Vista Rainbar | Recycle Bin
Description=A recycle bin gadget.
Instructions=Configure the drives being watched for trash through the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Recycle Bin
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com


[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=74
h=100
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Set][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Set][!HideMeter Close][!Redraw]
BackgroundMode=1
Update=5000
UpdateDivider=10

[Variables]
Drives=C:|
@Include=settings.inc

###

[MeasureBin]
Measure=Plugin
Plugin=RecycleManager.dll
RecycleType=COUNT
Drives=#Drives#

###

[BinEmpty]
Meter=IMAGE
ImageName=BinEmpty1.png
W=53
H=64
Hidden=0
LeftMouseUpAction=!RainmeterPluginBang "MeasureBin OpenBin"

MouseActionCursor=0

[BinFull]
Meter=IMAGE
ImageName=BinFull1.png
W=53
H=64
Hidden=1
LeftMouseUpAction=!RainmeterPluginBang "MeasureBin OpenBin"
MouseActionCursor=0

[BinAction]
Measure=Calc
Formula=MeasureBin
IfAboveAction=!execute [!HideMeter BinEmpty][!ShowMeter BinFull]
IfAboveValue=0
IfEqualAction=!execute [!HideMeter BinFull][!ShowMeter BinEmpty]
IfEqualValue=0

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=54
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=54
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=54
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Recycle Bin" "3.ini"
Hidden=1
