[Metadata]
Name=Media Player Gadget | WMP | Style 2
Config=Vista Rainbar | Media Player
Description=A gadget to control music playback of Window Media Player.
Version=5.0
Tags=Gadget | Vista Rainbar | Music
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png


[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

ContextTitle=Settings
ContextAction=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
ContextTitle2=Close
ContextAction2=!DeactivateConfig
ContextTitle3=Collapse
ContextAction3=!ActivateConfig "#currentconfig#"
ContextTitle4=----
ContextAction4=[]
ContextTitle5=More Actions
ContextAction5=[!SkinMenu]
Update=2000

[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=396
h=150
MouseOverAction=!execute [!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Close][!Redraw]

[Variables]
@include=UserVariables.inc

[mPlayer]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=TITLE
PlayerPatH=
DisableLeadingZero=0
Substitute="":"-"
; Return value is 1 on error
IfEqualValue=1
IfEqualAction=[!ShowMeter ErrorMessage][!Redraw]


[mStateButtan]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=STATE
Substitute="0":"Play.png","1":"Pause.png","2":"Play.png"

[mArtist]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=ARTIST
Substitute="":"-"


[mRating]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=RATING

[mYear]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=YEAR

[mGenre]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=GENRE

[mAlbum]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=ALBUM
Substitute="":"-"

[mCover]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=COVER
Substitute="":"#currentpath#\Default.png"

[mPosition]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=POSITION

[mDuration]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=DURATION

[mBadYearlyProgress]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=[mPlayer]
PlayerType=PROGRESS


[bg]
Meter=image
ImageName=Expanded#Light_Theme#.png






[Prev]
Meter=BUTTON
ButtonImage=Previous.png
X=259
Y=60
ButtonCommand=[!CommandMeasure mPlayer Previous][!Update]

[Play]
Meter=BUTTON
ButtonImage=[mStateButtan]
DynamicVariables=1
X=292
Y=47
ButtonCommand=[!CommandMeasure mPlayer PlayPause][!Update]


[Shuffle]
Meter=BUTTON
ButtonImage=Shuffle.png
X=304
Y=15
ButtonCommand=[!CommandMeasure mPlayer Shuffle -1][!Update]

[Stop]
Meter=BUTTON
ButtonImage=Stop.png
X=304
Y=104
ButtonCommand=[!CommandMeasure mPlayer Stop][!Update]

[Next]
Meter=BUTTON
ButtonImage=Next.png
X=348
Y=60
ButtonCommand=[!CommandMeasure mPlayer Next][!Update]

[Extra]
Meter=BUTTON
ButtonImage=WMPLancement.png
X=277
Y=35
ButtonCommand=!execute [!CommandMeasure mPlayer OpenPlayer]

[Volume]
Meter=BUTTON
ButtonImage=Volume.png
X=276
Y=99
ButtonCommand=!execute [!CommandMeasure mPlayer ClosePlayer]

[MeasureTimer]
Measure=Calc
Formula=(MeasureTimer + 1) % #AutoSkipSeconds#
IfCondition=(MeasureTimer = 0)
IfTrueAction=[!CommandMeasure "mPlayer" "Next"][!CommandMeasure "mPlayer" "SetPosition #AutoSkipPosition#"]
DynamicVariables=1
Disabled=#AutoSkip#


[Collapse]
Meter=BUTTON
ButtonImage=Collapse.png
X=6
Y=70
ToolTipText=Collapse
ButtonCommand=!ActivateConfig "#currentconfig#"



[MeterAlbumdE]
Meter=Image
MeasureName=mCover
MeterStyle=Full
x=100
y=(12)
w=(125)
h=(125)
ImageAlpha=255
Group=PROGRESSNot
Hidden=1

[MeterAlbumd]
Meter=Image
MeasureName=mCover
MeterStyle=Full
x=100
y=(12)
w=(125)
h=(125)
ImageAlpha=155
Group=PROGRESS



[Rating]
Meter=Image
ImageName=Rating[mRating].png
DynamicVariables=1
X=48
Y=18
Group=PROGRESS

[Time]
Meter=String
MeterStyle=Te
MeasureName=mPosition
MeasureName2=mDuration
TExtAlign=center
X=120
Y=18
Text="%1 / %2"

[Bitrate]
Meter=String
MeterStyle=Te
MeasureName=mPosition
MeasureName2=mDuration
TExtAlign=right
X=195
Y=18
w=50
Text="192kbps"

[HideProgress]
Meter=BUTTON
ButtonImage=HideProgress.png
X=252
Y=14
w=50
ButtonCommand=!execute [!ToggleMeterGroup ProgressNot][!ToggleMeterGroup Progress][!Redraw]

[Progress]
Meter=BAR
MeasureName=mBadYearlyProgress
X=50
Y=35
W=200
H=4
BarColor=255,255,255
SolidColor=90,158,207
BarOrientation=HORIZONTAL
LeftMouseUpAction=[!CommandMeasure "mStateButtan" "SetPosition $MouseX:%$"][!Update]
MouseActionCursor=1
Group=PROGRESS
[Te]
StringAlign=LEFT
AntiAlias=1
StringStyle=NORMAL
W=200
H=15
X=50
ClipString=1
Y=16r
FontColor=255,255,255
FontSize=8
StringEffect=Border
FontEffectColor=42,210,243,100
Group=PROGRESS

[song]
Meter=String
Y=50
MeterStyle=Te
MeasureName=mPlayer
FontColor=100,255,100
FontSize=10
[artist]
Meter=String
MeterStyle=Te
MeasureName=mArtist

[album]
Meter=String
MeterStyle=Te
MeasureName=mAlbum


[year]
Meter=String
MeterStyle=Te
MeasureName=mYear
Hidden=#Show_Year#
[genre]
Meter=String
MeterStyle=Te
MeasureName=mGenre
Hidden=#Show_Genre#
[Close1]
Meter=BUTTON
ButtonImage=Exit.png
X=346
Y=34
ButtonCommand=!execute ["%USERPROFILE%\Music"]

###

[Close]
Meter=BUTTON
ButtonImage=#@#\Graphics\Sidebar\Dropdown.png
X=370
Y=5
ButtonCommand=!SkinCustomMenu
Hidden=1
