[Metadata]
Name=Mail Gadget (Gmail) | Style 1
Config=Vista Rainbar | Mail | Gmail
Description=Alerts you about unread messages in your Gmail inbox.
Version=5.0
Tags=Gadget | Vista Rainbar | Mail
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=..\img\Fond2.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Set][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Set][!HideMeter Close][!Redraw]
Update=1000

[Variables]
TextG=<text on gadget>
@Include=..\settings.inc
Client=www.google.com/mail
FontName=Segoe UI
TxtColor=255,255,255,245
ShwColor=0,0,0,245

###

[MeasureGMail]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=https://#UserG#:#PasswordG#@gmail.google.com/gmail/feed/atom
RegExp="(?siU)<fullcount>(.*)</fullcount>"
Codepage=0
Download=1
UpdateRate=300
StringIndex=4

[MeasureMail]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[MeasureGMail]
StringIndex=1
UpdateRate=1
IfAboveValue=0
IfAboveAction=!execute [PLAY Notify.wav]

###

[NewShw]
Meter=STRING
MeasureName=MeasureMail
X=86
Y=12
FontFace=Segoe UI
FontColor=#ShwColor#
StringStyle=bold
fontSize=14
StringAlign=CENTER
Antialias=1

[New]
Meter=STRING
MeasureName=MeasureMail
X=1r
Y=-1r
FontFace=Segoe UI
FontColor=247,148,53
StringStyle=bold
fontSize=14
StringAlign=CENTER
Antialias=1

[MailShw]
Meter=STRING
X=86
Y=34
FontFace=Segoe UI
FontColor=#ShwColor#
StringStyle=bold
fontSize=9
StringAlign=CENTER
Antialias=1
Text=e-mail(s)

[Mail]
Meter=STRING
X=1r
Y=-1r
FontFace=Segoe UI
FontColor=#TxtColor#
StringStyle=bold
fontSize=9
StringAlign=CENTER
Antialias=1
Text=e-mail(s)

[Icon]
Meter=IMAGE
ImageName=#@#img\Mail.png
X=8
Y=6
W=50
H=50
RightMouseDownAction=!RainmeterRefresh
MouseOverAction=!execute [!ShowMeter Icon2][!Redraw]
MouseLeaveAction=!execute [!HideMeter Icon2][!Redraw]
MouseActionCursor=1

[Icon2]
Meter=IMAGE
ImageName=#@#img\Mail.png
X=4
Y=2
W=58
H=58
Hidden=1

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXSR.png
X=130
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=130
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=130
Y=21
ButtonCommand=!Execute ["#SKINSPATH#Vista Rainbar\Mail\MailConfig.exe"]
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=130
Y=42
ButtonCommand=!ActivateConfig "Vista Rainbar\Mail\Gmail" "3.ini"
Hidden=1
