[Metadata]
Name=Disk Gadget (1) | Style 2
Config=Vista Rainbar | Disk | 1
Description=Displays the usage of disk.
Version=5.0
Tags=Gadget | Vista Rainbar | Disk
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
Update=10000
MouseActionCursor=0
Author=legace@inbox.com

Background=..\img\Disque1.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=160
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Close][!Redraw]

[Variables]
Disk1=C:
NumOfDec=0
@Include=..\settings.inc
FontName2=Microsoft Sans Serif
TxtColor=255,255,255,225
Shw_Color=0,0,0,200
UpdateRate=14400

[MeasureDiskFree]
Measure=FreeDiskSpace
Drive=#Disk1#
Substitute="G":"GB","M":"MB","K":"KB"

[MeasureDiskUsed]
Measure=FreeDiskSpace
Drive=#Disk1#
InvertMeasure=1
Substitute="G":"GB","M":"MB","K":"KB"

[MeasureDiskTotal]
Measure=FreeDiskSpace
Drive=#Disk1#
Total=1
Substitute="G":"GB"

###

[DiskTotalBar]
MeasureName=MeasureDiskTotal
Meter=BAR
X=26
Y=36
H=5
W=113
BarColor=255,255,255,155
BarOrientation=HORIZONTAL

[DiskFreeBar]
MeasureName=MeasureDiskUsed
Meter=BAR
X=26
Y=36
H=5
W=113
BarImage=..\img\Bar.png
BarOrientation=HORIZONTAL

[DiskFree]
Meter=STRING
MeasureName=MeasureDiskFree
X=142
Y=10
FontColor=#Shw_Color#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Text="Free %1"

[DiskFree2]
Meter=STRING
MeasureName=MeasureDiskFree
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Text="Free %1"

[DiskUsed]
Meter=STRING
MeasureName=MeasureDiskUsed
X=142
Y=23
FontColor=#Shw_Color#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Text="Used %1"

[DiskUsed2]
Meter=STRING
MeasureName=MeasureDiskUsed
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=Bold
FontSize=8
StringAlign=right
FontFace=#FontName2#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Text="Used %1"

[DiskTotal.txt]
Meter=STRING
MeasureName=MeasureDiskTotal
X=142
Y=10
FontColor=#Shw_Color#
StringStyle=BOLD
FontSize=8
StringAlign=RIGHT
FontFace=#FontName2#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Prefix="#Disk1#  "
hidden=1

[DiskTotal.txt2]
Meter=STRING
MeasureName=MeasureDiskTotal
X=1r
Y=-1r
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=8
StringAlign=RIGHT
FontFace=#FontName2#
AntiAlias=1
AutoScale=1
NumofDecimals=#NumOfDec#
Prefix="#Disk1#  "
hidden=1

[FreePercent]
Meter=STRING
MeasureName=MeasureDiskFree
X=142
Y=23
FontColor=#Shw_Color#
FontFace=#FontName2#
FontSize=8
StringAlign=right
StringStyle=bold
AntiAlias=1
Percentual=1
Text="Free Space %1%"
Hidden=1

[FreePercent2]
Meter=STRING
MeasureName=MeasureDiskFree
X=1r
Y=-1r
FontColor=#TxtColor#
FontFace=#FontName2#
FontSize=8
StringAlign=right
StringStyle=bold
AntiAlias=1
Percentual=1
Text="Free Space %1%"
Hidden=1

[ME_c]
Meter=IMAGE
X=16
Y=10
W=42
H=22
MouseOverAction=!execute [!HideMeter DiskFree][!HideMeter DiskFree2][!HideMeter DiskUsed][!HideMeter DiskUsed2][!ShowMeter DiskTotal.txt][!ShowMeter DiskTotal.txt2][!ShowMeter FreePercent][!ShowMeter FreePercent2][!ShowMeter DiskTotal.txt][!ShowMeter DiskTotal.txt2][!Redraw]
MouseLeaveAction=!execute [!ShowMeter DiskFree][!ShowMeter DiskFree2][!ShowMeter DiskUsed][!ShowMeter DiskUsed2][!HideMeter DiskTotal.txt][!HideMeter DiskTotal.txt2][!HideMeter FreePercent][!HideMeter FreePercent2][!HideMeter DiskTotal.txt][!HideMeter DiskTotal.txt2][!Redraw]

[HDDIcon]
Meter=BUTTON
ButtonImage=#@#img\HDD1Button.png
X=0
Y=-25
ButtonCommand=!Execute [#Disk1#]

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXR.png
X=149
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=149
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=149
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\Disk\1" "3.ini"
Hidden=1
