[Metadata]
Name=CPU Meter | Style 2
Config=Vista Rainbar | CPU Meter
Description=Displays the CPU and RAM usage.
Version=5.0
Tags=Gadget | Vista Rainbar | CPU | RAM | System
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Background=CPUMeterBlack.png
[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=150
h=150
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter More][!ShowMeter Back][!ShowMeter Close][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter More][!HideMeter Back][!HideMeter Close][!Redraw]

[Variables]
FontName=Segoe UI
TxtColor=255,255,255,235
Shw_Color=0,0,0,200
AntiAlias=1

###

[MeasureCPU]
Measure=CPU

###

[CPU]
MeasureName=MeasureCPU
Meter=ROTATOR
X=42
Y=57
ImageName=RotatorBlack.png
StartAngle=1
RotationAngle=4.2832
OffsetX=5
OffsetY=30

[CPU2]
MeasureName=MeasureCPU
Meter=STRING
X=44
Y=78
FontColor=#TxtColor#
StringStyle=BOLD
FontSize=7
StringAlign=CENTER
FontFace=#FontName#
Postfix="%"
AntiAlias=1

---
[MeasurePhysUsed]
Measure=PhysicalMemory

[UsedPhysMemBar]
MeasureName=MeasurePhysUsed
Meter=ROTATOR
X=96
Y=36
ImageName=RotatorRAMBlack.png
StartAngle=1
RotationAngle=4.2832
OffsetX=4
OffsetY=21

[PhysMemUsed]
Meter=string
MeasureName=MeasurePhysUsed
X=97
Y=44
FontColor=#TxtColor#
StringStyle=bold
FontSize=7
StringAlign=CENTER
FontFace=#FontName#
AntiAlias=1
Postfix="%"
AutoScale=1
Percentual=1

---
[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXRL.png
X=130
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=130
Y=0
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[More]
Meter=BUTTON
ButtonImage=#@#img\More.png
X=130
Y=21
ButtonCommand=!ActivateConfig "Vista Rainbar\CPU Meter" "3.ini"
Hidden=1

[Back]
Meter=BUTTON
ButtonImage=#@#img\Back.png
X=130
Y=42
ButtonCommand=!ActivateConfig "Vista Rainbar\CPU Meter" "1.ini"
Hidden=1
