[Metadata]
Name=Slideshow Gadget | Normal
Config=Vista Rainbar | Slideshow
Description=Displays a slideshow of pictures from selected folder.
Instructions=Use configuration tool to set picture folder.
Version=5.0
Tags=Gadget | Vista Rainbar | Slideshow
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png

[Rainmeter]
Group=Gadget | Vista Rainbar
MiddleMouseUpAction=!DeactivateConfig
MouseActionCursor=0
Author=legace@inbox.com

Update=(#Slideshow_Speed#*60000)


[img]
Meter=IMAGE
w=130
h=100
y=10
ImageName=frame#Beta_Style#.png


[Solid]
Meter=STRING
solidcolor=0,0,0,1
w=140
h=100
MouseOverAction=!execute [!ShowMeter Popup][!ShowMeter Pause][!ShowMeter Next][!ShowMeter Explorer][!ShowMeter Previous][!ShowMeter Menu][!ShowMeter Close][!ShowMeter Plus][!ShowMeter Set][!Redraw]
MouseLeaveAction=!execute [!HideMeter Popup][!HideMeter Pause][!HideMeter Next][!HideMeter Previous][!HideMeter Explorer][!HideMeter Menu][!HideMeter Close][!HideMeter Plus][!HideMeter Set][!Redraw]


[Variables]
@Include=UserVariables.inc
Beta_Style=0

###

[Random]
Measure=Plugin
Plugin=Plugins\QuotePlugin.dll
PathName="#Pictures_Folder#"
Subfolders=1
FileFilter=*.jpg;*.jpeg;*.gif;*.png

###

[Image]
MeasureName=Random
Meter=IMAGE
X=4
Y=15
W=120
H=90

[PopUp]
Meter=IMAGE
ImageName=bg_sidebar.png
X=8
Y=78
Hidden=1

[Previous]
Meter=BUTTON
ButtonImage=prev.png
X=15
Y=81
ButtonCommand=!Execute [!RainmeterRefresh]
Hidden=1

[Pause]
Meter=BUTTON
ButtonImage=pause.png
X=41
Y=81
Hidden=1

[Next]
Meter=BUTTON
ButtonImage=Next.png
X=64
Y=81
ButtonCommand=!Execute [!RainmeterRefresh]
Hidden=1

[Explorer]
Meter=BUTTON
ButtonImage=explorer.png
X=88
Y=81
ButtonCommand=!Execute ["[Random]"]
Hidden=1

###

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXPS.png
X=118
Y=10
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=10
ButtonCommand=!RainmeterDeactivateConfig
Hidden=1

[Plus]
Meter=BUTTON
ButtonImage=#@#img\Plus.png
X=118
Y=31
ButtonCommand=!Execute [!ActivateConfig "Vista Rainbar\Slideshow" "Normal+.ini"][!RainmeterRefresh]
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=52
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1