[Metadata]
Name=Weather Gadget #1 | Style 1
Config=Vista Rainbar | Weather | 1
Description=Shows the current weather conditions.
Instructions=Set your Weather codes to show your location using the configuration tool.
Version=5.0
Tags=Gadget | Vista Rainbar | Weather
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Preview=#SKINSPATH#Vista Rainbar\img\Preview.png


[Rainmeter]
Group=Gadget | Vista Rainbar
MouseActionCursor=0
Author=legace@inbox.com

BackgroundMode=0
MiddleMouseUpAction=!DeactivateConfig
Update=2000
MouseOverAction=!execute [!ShowMeter Menu][!ShowMeter Set][!ShowMeter Close][!ShowMeter Plus][!Redraw]
MouseLeaveAction=!execute [!HideMeter Menu][!HideMeter Set][!HideMeter Close][!HideMeter Plus][!Redraw]

[Variables]
City1=Helsinki
State1=FI
Zip1=FIXX0020
Unit=c
Palmtree=N

FontName=Segoe UI
TxtColor=255,255,255,245
ShwColor=0,0,0
@include=settings.inc
@include2=#currentpath#\UserVariables.inc
@Include3=#@#WeatherComJSONVariables.inc
@Include4=#@#WeatherComJSONMeasures5Day.inc

###






[MeasureTime]
Measure=Time
Format=%H


[MeasureDay]
Measure=TIME
Format=%d
;TimeZone=#_TimeZone#
DaylightSavingTime=#_DayLightSavingsTime#

[MeasureMonth]
Measure=TIME
Format=%m
;TimeZone=#_TimeZone#
DaylightSavingTime=#_DayLightSavingsTime#

[MeasureYear]
Measure=TIME
Format=%Y
;TimeZone=#_TimeZone#

[MeasureDaysSinceY2K]
Measure=Calc
Formula=FLOOR((MeasureYear-2000)*365.25)+(MeasureMonth>1)*31+(MeasureMonth>2)*(28+((MeasureYear%4)=0))+(MeasureMonth>3)*31+(MeasureMonth>4)*30+(MeasureMonth>5)*31+(MeasureMonth>6)*30+(MeasureMonth>7)*31+(MeasureMonth>8)*31+(MeasureMonth>9)*30+(MeasureMonth>10)*31+(MeasureMonth>11)*30+(MeasureMonth>12)*31+MeasureDay

[MeasureMoonPhase]
Measure=Calc
Formula=ROUND(16*FRAC(((-29.5305888531)+SQRT((29.5305888531)**2-4*(102.19*(10**(-12)))*(20.362954-MeasureDaysSinceY2K)))/(2*(102.19*(10**(-12))))))%16
Substitute=".00000":""

[MeasureLuaScript]
Measure=SCRIPT
ScriptFile=#CURRENTPATH#Sun.lua




[MeasureBlack]
Measure=Calc
Formula=((MeasureTime + 0) < #_RiseHours#) || ((MeasureTime + 0) > (#_SetHours#)) ? (1) : (-1)
IfAboveValue=0
IfAboveAction=!Execute [!SetOption Title FontEffectColor 0,0,0,100][!SetOption Temp FontEffectColor 0,0,0,100][!SetOption Temp FontColor 255,255,255][!SetOption Title FontColor 255,255,255][!ShowMeter Black][!HideMeter Blue][!ShowMeter BlackDeco][!HideMeter BlueDeco]
IfBelowValue=0
IfBelowAction=!Execute [!SetOption Title FontEffectColor 0,0,0,0][!SetOption Temp FontEffectColor 0,0,0,0][!SetOption Temp FontColor 0,0,0][!SetOption Title FontColor 0,0,0][!HideMeter Black][!ShowMeter Blue][!HideMeter BlackDeco][!ShowMeter BlueDeco]
DynamicVariables=1




[MeasureOrange]
Measure=Calc
Formula=(MeasureTime = #_SetHours#) ? (1) : (-1)
IfAboveValue=0
IfAboveAction=!Execute [!ShowMeter Orange][!ShowMeter OrangeDeco][!Redraw]
IfBelowValue=0
IfBelowAction=!Execute [!HideMeter Orange][!HideMeter OrangeDeco][!Redraw]
DynamicVariables=1

[MeasureGrey]
Measure=Calc
Formula=(((MeasureTime + 0) < #_RiseHours#) || ((MeasureTime + 0) > (#_SetHours#))) || ((@CurrentIcon = 29) || (@CurrentIcon = 30) || (@CurrentIcon = 31) || (@CurrentIcon = 32) || (@CurrentIcon = 33) || (@CurrentIcon = 34) || (@CurrentIcon = 36) || (@CurrentIcon = 37) || (@CurrentIcon = 39) || (@CurrentIcon = 44)) ? (1) : (-1)
IfAboveValue=0
IfAboveAction=!Execute [!HideMeter Grey][!Redraw]
IfBelowValue=0
IfBelowAction=!Execute [!ShowMeter Grey][!Redraw]
DynamicVariables=1

[MeasureMoon]
Measure=Calc
Formula=(((MeasureTime + 0) < #_RiseHours#) || ((MeasureTime + 0) > (#_SetHours# ))) && ((@CurrentIcon=31) || (@CurrentIcon=32) || (@CurrentIcon=33) || (@CurrentIcon=34) || (@CurrentIcon=36)) ? (1) : (-1)
IfAboveValue=0
IfAboveAction=!Execute [!ShowMeter Moon][!Redraw]
IfBelowValue=0
IfBelowAction=!Execute [!HideMeter Moon][!Redraw]
DynamicVariables=1

[MeasureSun]
Measure=Calc
Formula=(((MeasureTime + 0) > (#_RiseHours# - 1)) && ((MeasureTime + 0) < (#_SetHours#))) && ((@CurrentIcon=31) || (@CurrentIcon=32) || (@CurrentIcon=33) || (@CurrentIcon=34) || (@CurrentIcon=36)) ? (1) : (-1)
IfAboveValue=0
IfAboveAction=!Execute [!ShowMeter Sun][!Redraw]
IfBelowValue=0
IfBelowAction=!Execute [!HideMeter Sun][!Redraw]
DynamicVariables=1




###

[Blue]
Meter=IMAGE
ImageName=#@#weather\Bleu.png
Hidden=1

[Black]
Meter=IMAGE
ImageName=#@#weather\Black.png
Hidden=1

[Orange]
Meter=IMAGE
ImageName=#@#weather\Orange.png
Hidden=1

[Grey]
Meter=IMAGE
ImageName=#@#weather\Gris.png
Hidden=1

[MeasureMoonPhaseMod]
Measure=Calc
Formula=880000+(MeasureMoonPhase*100)+97
Substitute="88":"#@#\moon\","97":".png"

[Moon]
Meter=IMAGE
MeasureName=MeasureMoonPhaseMod
Hidden=1
ImageCrop=-150,-120,160,102,3
x=3
y=3
w=95




[Sun]
Meter=IMAGE
ImageName=#@#weather\Sun.png
Hidden=1

[Pixel]
Meter=IMAGE
ImageName=.\Pixel.png
x=2
y=1

[Icon]
Meter=IMAGE
MeasureName=@CurrentIcon
ImagePath=#@#\weather\

DynamicVariables=1

[BlackDeco]
Meter=IMAGE
ImageName=#@#weather\BlackDeco#Palmtree#.png
Hidden=1

[BlueDeco]
Meter=IMAGE
ImageName=#@#weather\BlueDeco#Palmtree#.png
Hidden=1

[OrangeDeco]
Meter=IMAGE
ImageName=#@#weather\OrangeDeco#Palmtree#.png
Hidden=1


[Temp]
Meter=STRING
MeasureName=@CurrentTemperature
X=129
Y=-2
FontColor=#TxtColor#
FontSize=22
StringAlign=RIGHT
StringStyle=NORMAL
FontFace=#FontName#
Antialias=1
Postfix=°
StringEffect=SHADOW
FontEffectColor=0,0,0,100
ToolTipText=Sunset: #_SetHours#
DynamicVariables=1

[Title]
Meter=STRING
X=125
Y=35
H=15
W=118
FontColor=#TxtColor#
FontSize=9
StringStyle=BOLD
StringAlign=RIGHT
Clipstring=1
FontFace=#FontName#
Antialias=1
MeasureName=@LocationName
LeftMouseUpAction=["http://weather.com/"]
MouseActionCursor=1
StringEffect=SHADOW
FontEffectColor=0,0,0,100

[NA]
Meter=IMAGE
ImageName=#@#weather\NA.png
Hidden=1

[Menu]
Meter=IMAGE
ImageName=#@#img\MenuXPS.png
X=118
Y=0
Hidden=1

[Close]
Meter=BUTTON
ButtonImage=#@#img\Close.png
X=118
Y=0
ButtonCommand=!DeactivateConfig
Hidden=1

[Plus]
Meter=BUTTON
ButtonImage=#@#img\Plus.png
X=118
Y=21
ButtonCommand=!Execute [!ActivateConfig "Vista Rainbar\Weather\1" "1+.ini"][!Refresh]
Hidden=1

[Set]
Meter=BUTTON
ButtonImage=#@#img\Settings.png
X=118
Y=42
ButtonCommand=!execute ["#@#\Config.exe" "#CURRENTCONFIG#" "#currentpath#\" "#CURRENTFILE#" "#programpath#\" "#CURRENTCONFIGX#" "#CURRENTCONFIGY#"]
Hidden=1

